export function buildWebsocketsSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      message:     'WebSockets: persistent bidirectional communication over a single TCP connection',
      detail:      'HTTP is a request-response protocol — the client always initiates. Real-time apps (chat, live dashboards, multiplayer games) need the server to push data without waiting for a client request. WebSockets solve this by upgrading an HTTP connection into a persistent bidirectional channel.',
    },
    {
      type:        'http-polling',
      activeNodes: ['client', 'channel'],
      connections: { 'client-channel': 'both' },
      pollingState: 'polling',
      message:     'Problem: HTTP polling wastes bandwidth and adds latency',
      detail:      'Without WebSockets, clients must poll: GET /messages every second. Most responses are empty ("nothing new"). At 1000 concurrent users polling every second: 1000 HTTP requests/second — each with full headers, TLS overhead, and a new TCP connection (if not using keep-alive). Latency equals the polling interval, not the actual event time.',
    },
    {
      type:        'ws-upgrade',
      activeNodes: ['client', 'channel', 'server'],
      connections: { 'client-channel': 'request', 'channel-server': 'request' },
      pollingState: null,
      connectionState: 'upgrading',
      message:     'WebSocket upgrade — HTTP 101 Switching Protocols',
      detail:      'The client sends a normal HTTP GET with Upgrade: websocket and Sec-WebSocket-Key headers. The server responds 101 Switching Protocols with Sec-WebSocket-Accept (a hash of the key). The TCP connection is kept open — it\'s now a WebSocket connection. The entire handshake takes 1 RTT and reuses the existing TLS session.',
    },
    {
      type:        'persistent-connection',
      activeNodes: ['client', 'channel', 'server'],
      connections: { 'client-channel': 'both', 'channel-server': 'both' },
      connectionState: 'open',
      message:     'Persistent connection — either side sends frames at any time',
      detail:      'After the upgrade, both client and server can send WebSocket frames at any time without waiting for the other side. Frames are small (2-byte header minimum vs HTTP\'s ~400-byte header). Binary or text payloads. No polling overhead. The connection stays alive until either side sends a close frame or the TCP connection drops.',
    },
    {
      type:        'server-push',
      activeNodes: ['server', 'channel', 'client'],
      connections: { 'channel-server': 'request', 'client-channel': 'both' },
      connectionState: 'open',
      message:     'Server push — server sends messages without a client request',
      detail:      'The server pushes updates the instant an event occurs — a new chat message, a stock price change, a live game score. The client receives data with latency limited only by network RTT, not by polling interval. Contrast with Server-Sent Events (SSE) which is server-to-client only — WebSockets are fully bidirectional.',
    },
    {
      type:        'heartbeat',
      activeNodes: ['client', 'channel', 'server'],
      connections: { 'client-channel': 'both', 'channel-server': 'both' },
      connectionState: 'open',
      pingState: 'pinging',
      message:     'Heartbeat — ping/pong frames keep connections alive through proxies',
      detail:      'Idle TCP connections are closed by load balancers and proxies (typically after 60–120s). WebSocket ping/pong frames prevent this. The server sends a Ping frame every 30s; the client responds with Pong automatically. If no Pong arrives within the timeout, the server closes the connection. Clients should also send heartbeats to detect server-side failures.',
    },
    {
      type:        'reconnect',
      activeNodes: ['client', 'channel'],
      connections: { 'client-channel': 'request' },
      connectionState: 'reconnecting',
      message:     'Reconnection — clients must handle disconnects with exponential backoff',
      detail:      'WebSocket connections drop due to network blips, server restarts, or load balancer timeouts. The client must detect the close event (onclose) and reconnect with exponential backoff (1s, 2s, 4s, 8s…) to avoid thundering herds. After reconnection, the client should re-subscribe to channels and request any missed messages (sequence numbers or timestamps help here).',
    },
    {
      type:        'scaling',
      activeNodes: ['client', 'channel', 'server'],
      connections: { 'client-channel': 'both', 'channel-server': 'both' },
      connectionState: 'open',
      message:     'Scaling WebSockets — sticky sessions or shared pub/sub (Redis)',
      detail:      'Each server holds state for its open connections in memory. Horizontal scaling is the challenge: if Client A is on Server 1 and sends a message to Client B on Server 2, how does Server 2 know? Solution: sticky sessions (load balancer routes each client to the same server) or a shared pub/sub layer (Redis Pub/Sub, Kafka). Most production WebSocket systems use Redis for cross-node message fanout.',
    },
    {
      type:        'use-cases',
      activeNodes: ['client', 'channel', 'server'],
      connections: { 'client-channel': 'both', 'channel-server': 'both' },
      connectionState: 'open',
      message:     'Use cases — chat, live dashboards, collaborative editing, gaming',
      detail:      'WebSockets excel whenever the server needs to push data without client polling: real-time chat (Slack, Discord), live dashboards (Grafana, trading terminals), collaborative editing (Notion, Figma), multiplayer games. For unidirectional server push (live feeds, notifications), SSE is simpler and works over HTTP/1.1. For fire-and-forget metrics, UDP or QUIC may be preferable.',
    },
  ]
}
