export default {
  id:          'http',
  type:        'concept',
  title:       'HTTP',
  category:    'apis',
  tags:        ['http', 'https', 'tls', 'request', 'response', 'stateless', 'rest', 'http2', 'http3', 'quic', 'keep-alive', 'multiplexing', 'status-codes', 'headers'],
  description: 'The request-response protocol powering the web. A client sends a request (method, path, headers, body); a server returns a response (status code, headers, body). Every exchange is stateless and self-contained — the server holds no memory between requests, which is what makes HTTP services easy to scale horizontally.',
  metaphor:    'A waiter taking orders (requests) and returning with food (responses). Each visit is independent — the waiter remembers nothing between trips, and every order must carry full context: who you are, what you want, what format you expect. Handing the waiter a menu card (headers) alongside your order is how you pass that context every time.',
  path:        '/system-design/http',
  howItWorks: [
    'Request anatomy: a request has three parts. The request line (method + path + version: "GET /api/users HTTP/1.1"), followed by headers (key-value metadata: Host, Accept, Authorization, Content-Type), then an optional body. GET and DELETE have no body; POST, PUT, and PATCH carry a payload. Headers are case-insensitive and sent as plain text in HTTP/1.x.',
    'Response anatomy: a response has a status line (version + code + reason: "HTTP/1.1 200 OK"), response headers (Content-Type, Content-Length, Cache-Control, Set-Cookie), then the optional body. The blank line separating headers from body is significant — parsers use it as the boundary.',
    'Status codes: the three-digit code tells the client exactly what happened. 2xx = success (200 OK, 201 Created, 204 No Content). 3xx = redirect (301 Permanent, 302 Temporary, 304 Not Modified — serve from cache). 4xx = client error (400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 429 Too Many Requests). 5xx = server error (500 Internal Error, 502 Bad Gateway, 503 Unavailable).',
    'Statelessness: the server holds zero session state between requests. Each request must carry all necessary context — identity (Authorization header or session cookie), content negotiation (Accept), connection preferences (Connection: keep-alive). Statelessness enables horizontal scaling: any server instance can handle any request since there is no sticky session state to worry about.',
    'HTTP/1.1 keep-alive: HTTP/1.0 opened a new TCP connection for every request — expensive when each connection costs a TCP handshake (1 RTT) plus a TLS handshake (1–2 RTT). HTTP/1.1 defaults to Connection: keep-alive, reusing the same TCP connection for multiple sequential request-response pairs. The limitation: requests are still serialized — request 2 waits for request 1\'s response (head-of-line blocking).',
    'HTTP/2 multiplexing: HTTP/2 introduces streams — independent request-response pairs sharing one TCP connection, each assigned an integer stream ID. Multiple streams run in parallel: three API calls that would take 3 × RTT sequentially take 1 × RTT in parallel. HTTP/2 also binary-frames data (faster to parse), compresses headers with HPACK (headers repeat verbatim on every HTTP/1.x request), and supports server push.',
    'HTTP/3 and QUIC: HTTP/2 still runs over TCP, which has its own head-of-line blocking — a dropped TCP packet stalls all streams until it is retransmitted. HTTP/3 replaces TCP with QUIC (UDP-based), which isolates packet loss per stream. QUIC also combines the TCP and TLS handshakes into a single 1-RTT (or 0-RTT for reconnections). Chrome and most major CDNs support HTTP/3 today.',
  ],
  keyPoints: [
    'HTTP is stateless — each request must include full context. This is a feature, not a limitation: it enables any server to handle any request, making horizontal scaling straightforward',
    'HTTP/1.1 keep-alive eliminates per-request TCP + TLS handshake overhead. Without it, a 50 ms RTT link adds 150 ms of handshake latency to every request',
    'HTTP/2 multiplexing collapses N sequential RTTs into 1 RTT by running N streams in parallel on one connection — critical for resource-heavy pages making dozens of API calls',
    'Status codes are the contract between client and server: 4xx means the client did something wrong (don\'t retry without fixing the request); 5xx means the server failed (safe to retry with backoff)',
    'HTTPS wraps HTTP in TLS — a requirement for any production API. TLS provides encryption, integrity, and server authentication. Without it, tokens and cookies are visible to any network observer',
    'HTTP/3 replaces TCP with QUIC to eliminate transport-level head-of-line blocking. A single dropped UDP packet no longer stalls all multiplexed streams — each stream recovers independently',
  ],
}
