export default {
  id:          'consistency-models-spectrum',
  type:        'concept',
  title:       'Spectrum of Consistency Models',
  category:    'framework',
  tags:        ['consistency', 'linearizability', 'sequential-consistency', 'causal-consistency', 'eventual-consistency', 'cap-theorem', 'distributed-systems', 'consistency-spectrum'],
  description: 'A ladder of consistency guarantees, from strongest (linearizability — behaves like there\'s only ever one copy of the data, with real-time recency) to weakest (eventual — replicas converge with no timing promise at all). Climbing the ladder buys stronger guarantees but costs latency and availability, especially under network partition. Picking the right rung for a given read path — not just "strong" or "eventual" as a binary — is one of the most consequential trade-offs in distributed systems.',
  metaphor:    "Four ways a group of friends share a running shopping list. Linearizable: everyone must call one phone number and speak to the single person holding the master list before adding anything — slow, but nobody ever sees a stale list, and the order matches real time exactly. Sequential: everyone agrees on one shared order of edits that respects each person's own sequence, like passing a physical notebook around — consistent, but not tied to wall-clock time. Causal: you only need to see the edits that causally came before yours (someone's reply to your addition); unrelated edits from other friends can arrive in any order. Eventual: everyone scribbles on their own copy and compares notes later — it all matches up eventually, but for a while your list and mine might disagree.",
  path:        '/system-design/consistency-models-spectrum',
  howItWorks: [
    'Linearizability (strong consistency): the system behaves as if there were exactly one copy of the data and every operation took effect atomically at some instant between its start and end, matching real (wall-clock) time. If write W finishes before read R begins, R must see W\'s result — no exceptions, regardless of which replica serves R. This is the strongest, most intuitive guarantee, and the most expensive: it requires coordinating a quorum of replicas on every write (and often every read), which adds latency and — per the CAP theorem — becomes impossible to guarantee during a network partition without sacrificing availability.',
    'Sequential consistency: weaker than linearizability in one specific way — it drops the real-time requirement. All operations still appear to execute in some single global order, and that order still respects each individual process\'s own program order, but the global order doesn\'t have to match wall-clock time. Concretely: if you and I each make a write, an observer must see them in *some* consistent order, but that order doesn\'t have to be "whoever\'s write actually finished first in real time." This relaxation is what makes sequential consistency cheaper to implement than linearizability while still being strong enough for many coordination problems.',
    'Causal consistency: weaker still — it only orders operations that are causally related. If write B was made after reading the result of write A (a reply to a comment, a message referencing an earlier one), every node must see A before B. Writes with no causal relationship (two unrelated users editing unrelated data) can be observed in different orders by different nodes without violating the guarantee. This is usually the sweet spot for social and collaborative applications: it prevents the "reply appeared before the original post" class of bug without paying for global ordering of unrelated events.',
    'Eventual consistency: the weakest useful guarantee — after writes stop arriving, all replicas will eventually converge to the same value, with no bound on how long "eventually" takes and no ordering guarantee in the meantime. Two readers hitting two different replicas mid-convergence can see different, even contradictory, states. This is what most NoSQL datastores default to, and it\'s cheap: no coordination is needed on the write path at all, which is why it scales and stays available through partitions that would stall a linearizable system.',
    'The cost of climbing the ladder is not academic — it\'s the direct, practical form of the CAP theorem\'s trade-off. Linearizability requires synchronous coordination, which is either slow (wait for a quorum) or unavailable (refuse the operation) when a partition prevents that coordination. Eventual consistency requires no coordination at all, so it stays fast and available through the same partition — at the cost of readers potentially seeing stale or conflicting data. Sequential and causal consistency sit in between, trading some coordination cost for a guarantee stronger than pure eventual consistency.',
    'This spectrum is the theoretical vocabulary; `consistency-patterns` in this app covers the practical, request-scoped patterns built on top of it — read-your-writes, monotonic reads, and session consistency are specific client-facing contracts that are usually implemented as causal or eventual consistency plus a bit of per-client bookkeeping (e.g. routing a user\'s own reads to the replica that has their own last write). Read that concept for how these rungs actually show up in a design; read this one for what the rungs mean and why they exist.',
  ],
  keyPoints: [
    'The ladder, strongest to weakest: linearizable → sequential → causal → eventual. Each step down trades a guarantee for lower latency and higher availability',
    'Linearizability = real-time recency (if a write finished, every later read sees it); sequential consistency drops only the real-time requirement, keeping a single agreed-upon order',
    'Causal consistency only orders operations that are causally related (a reply after its post) — concurrent, unrelated writes can be seen in different orders by different nodes, which is usually fine',
    'Eventual consistency is the cheapest: zero coordination on writes, replicas just converge given enough time — the default for most NoSQL stores because it\'s what lets them stay available through a partition',
    'This spectrum IS the CAP theorem\'s consistency axis made concrete — moving up the ladder is moving toward "C" and away from "A" during a partition, not a free upgrade',
    'This is the theoretical/vocabulary layer; see `consistency-patterns` for the practical client-facing contracts (read-your-writes, monotonic reads, session consistency) built on top of causal/eventual consistency',
  ],
  components: [
    {
      id:            'linearizable',
      title:         'Linearizable',
      icon:          '🔒',
      color:         '#f43f5e',
      animationType: 'consistency',
      summary: 'Strongest — behaves like a single copy, real-time recency guaranteed',
      detail:  'Every operation appears to take effect atomically at some point between its start and end, matching wall-clock time. Requires quorum coordination on every write. Used for distributed locks, leader election, financial balances — anywhere a stale read is a correctness bug, not just an inconvenience.',
      stats: [
        { label: 'Ordering',  value: 'Matches real time' },
        { label: 'Cost',      value: 'Highest latency' },
        { label: 'Use case',  value: 'Locks, balances' },
      ],
    },
    {
      id:            'sequential',
      title:         'Sequential',
      icon:          '📶',
      color:         '#f97316',
      animationType: 'consistency',
      summary: 'One agreed global order, respecting each process\'s own sequence — but not real time',
      detail:  'All nodes see operations in the same order, and that order respects each process\'s own program order — but it doesn\'t have to match wall-clock time. Cheaper than linearizability because it drops the real-time constraint while keeping a single global order.',
      stats: [
        { label: 'Ordering',  value: 'Single global order' },
        { label: 'Real-time?', value: 'Not required' },
        { label: 'Use case',  value: 'Coordination w/o clock sync' },
      ],
    },
    {
      id:            'causal',
      title:         'Causal',
      icon:          '🔗',
      color:         '#8b5cf6',
      animationType: 'consistency',
      summary: 'Only causally related operations are ordered — unrelated ones can arrive in any order',
      detail:  'If B happened after observing A (a reply to a post), every node sees A before B. Concurrent, unrelated writes may be seen in different orders on different nodes without breaking the guarantee — usually the sweet spot for social/collaborative apps.',
      stats: [
        { label: 'Ordering',  value: 'Causal only' },
        { label: 'Cost',      value: 'Moderate' },
        { label: 'Use case',  value: 'Comments, replies, feeds' },
      ],
    },
    {
      id:            'eventual',
      title:         'Eventual',
      icon:          '🌊',
      color:         '#10b981',
      animationType: 'consistency',
      summary: 'Weakest — replicas converge eventually, no ordering or timing guarantee meanwhile',
      detail:  'No coordination needed on the write path at all, so it\'s the cheapest and most available option — stays up through partitions that would stall stronger models. Readers can see stale or momentarily contradictory data during convergence. Default for most NoSQL datastores.',
      stats: [
        { label: 'Ordering',  value: 'None guaranteed' },
        { label: 'Cost',      value: 'Lowest latency' },
        { label: 'Use case',  value: 'Feeds, DNS, shopping carts' },
      ],
    },
  ],
}
