export default {
  id:          'computer-architecture',
  type:        'concept',
  title:       'Computer Architecture',
  category:    'hardware',
  tags:        ['cpu', 'cache', 'ram', 'disk', 'hardware', 'latency', 'moores-law'],
  description: 'Every computer is built from five core hardware components: CPU, RAM, GPU, Storage, and Network. The CPU sits at the centre — all data flows through it. Understanding how these components interact is the foundation of every system design decision.',
  metaphor:    "A busy restaurant kitchen: the chef (CPU) is the centre of everything — they direct prep cooks (GPU) for bulk work, grab ingredients from the counter (RAM) constantly, send runners to the pantry (SSD) for storage, and take orders from the front-of-house (NIC/Network).",
  path:        '/system-design/computer-architecture',
  howItWorks: [
    'Everything you use — apps, files, the OS — lives permanently on the SSD or HDD.',
    'When you open an app, the CPU copies it from storage into RAM, where it is about 1,000 times faster to access.',
    'The CPU reads each instruction from RAM, executes it, and writes the result back — billions of times per second.',
    'For graphics, AI, or video, the CPU offloads the work to the GPU, which can run thousands of tasks in parallel.',
    'Network requests are handed to the network card (NIC), which handles sending and receiving while the CPU keeps working on other things.',
    'When RAM fills up, the OS quietly spills the least-used data back to disk — causing a 1,000x slowdown until space is freed.',
  ],
  keyPoints: [
    'Storage is permanent but slow — your apps and files live here until you open them',
    'RAM is fast but temporary — everything currently running lives here and is lost on power-off',
    'The CPU is the hub — every other component just waits for it to ask for something',
    'The GPU handles parallel work — graphics, AI, and video all at once',
    'When RAM fills up, performance tanks — it is the most common bottleneck on any machine',
  ],
  components: [
    {
      id:            'disk',
      title:         'Disk (SSD / HDD)',
      icon:          '🗄️',
      color:         '#f59e0b',
      animationType: 'disk',
      summary: 'Permanent storage — everything here survives a reboot',
      detail:  'Your files, programs, and databases all live on disk. When you turn the computer off and back on, disk is the only place data stays intact — RAM forgets everything. SSDs are fast (~100 µs) and silent; HDDs use spinning platters and are slower (~10 ms) but cheaper per gigabyte.',
      stats: [
        { label: 'SSD Latency', value: '~100 µs' },
        { label: 'HDD Latency', value: '~10 ms' },
        { label: 'Capacity',    value: '1–4 TB' },
        { label: 'Persistent',  value: 'Yes' },
      ],
    },
    {
      id:            'ram',
      title:         'RAM',
      icon:          '🧠',
      color:         '#06b6d4',
      animationType: 'ram',
      summary: 'Fast scratch pad — holds everything the computer is actively working on',
      detail:  'When you open an app, it loads from disk into RAM so the CPU can reach it quickly. RAM is about 1,000× faster than an SSD but forgets everything when power is cut. Think of it as your desk: the bigger it is, the more you can have open at once without slowing down.',
      stats: [
        { label: 'Latency',    value: '~60 ns' },
        { label: 'Capacity',   value: '8–64 GB' },
        { label: 'Persistent', value: 'No' },
      ],
    },
    {
      id:            'cpu',
      title:         'CPU',
      icon:          '⚙️',
      color:         '#3b82f6',
      animationType: 'cpu',
      summary: 'The brain — runs every line of code on the computer',
      detail:  'The CPU fetches instructions from RAM, figures out what they mean, executes them, and writes the result back — billions of times per second. Every other component (RAM, disk, GPU) just sits and waits for the CPU to ask for something. Multiple cores let it handle many tasks at once.',
      stats: [
        { label: 'Clock Speed', value: '3–5 GHz' },
        { label: 'Cores',       value: '4–32' },
        { label: 'Cycle Time',  value: '~0.3 ns' },
      ],
    },
    {
      id:            'cache',
      title:         'L1 / L2 Cache',
      icon:          '⚡',
      color:         '#10b981',
      animationType: 'cache',
      summary: 'Tiny ultra-fast memory built directly onto the CPU chip',
      detail:  'Before going to RAM, the CPU checks cache first — a hit takes ~1 ns vs ~60 ns for RAM. Cache automatically holds the data you used most recently, betting you will need it again soon. When that bet pays off, your program runs dramatically faster. A cache miss forces the slower trip to RAM.',
      stats: [
        { label: 'L1 Latency', value: '~1 ns' },
        { label: 'L2 Latency', value: '~4 ns' },
        { label: 'L1 Size',    value: '32–64 KB' },
        { label: 'L2 Size',    value: '256 KB–1 MB' },
      ],
    },
  ],
}
