export default {
  id:          'application-architecture',
  type:        'concept',
  title:       'Application Architecture',
  category:    'architecture',
  tags:        ['architecture', 'client-server', 'frontend', 'cicd', 'load-balancer', 'cache', 'stateless', 'scalability'],
  description: 'How a production web application is structured — from the code a developer writes to the response a user receives. Every layer has a single job, and understanding each one tells you exactly where to look when things go wrong.',
  metaphor:    "A restaurant: the menu and decor are the frontend, the kitchen is the server, the pantry is the database, the pass-through window is the load balancer, the prep station reusing yesterday's sauces is the cache, and the health inspector watching everything is monitoring.",
  path:        '/system-design/application-architecture',
  howItWorks: [
    'A developer writes code and pushes it to a shared repository — every change is tracked and can be rolled back.',
    'The push triggers a CI/CD pipeline that builds the code, runs tests, and deploys automatically if everything passes.',
    'When a user opens the app, the CDN serves the frontend bundle — HTML, JavaScript, CSS, images — from a location close to them.',
    'The frontend app running in the browser makes API calls that hit the load balancer, which routes each one to a healthy backend server.',
    'The server checks the cache first. On a hit it returns data instantly. On a miss it queries the database and stores the result for next time.',
    'Monitoring collects logs, metrics, and traces from every layer. When something breaks, an alert fires before most users even notice.',
  ],
  keyPoints: [
    'CI/CD removes the human from deployments — changes ship faster, safer, and with an instant rollback path',
    'The CDN handles the bulk of traffic before a request ever reaches your backend servers',
    'Every server must be stateless — sessions and shared state belong in the cache or database, not on the server',
    'Cache sits between the server and database — a 90% hit rate means the database sees only 10% of read traffic',
    'You cannot fix what you cannot see — logging, metrics, and alerts are not optional in production',
  ],
  components: [
    {
      id:            'developer',
      title:         'Developer & Version Control',
      icon:          '👨‍💻',
      color:         '#6366f1',
      animationType: 'git',
      summary:       'Where every change begins — all code lives in version control',
      detail:        'Developers push changes to a shared repository (GitHub, GitLab). Every line is tracked, linked to a pull request, reviewed by teammates, and associated with a deploy. If a release breaks something, reverting to the previous version takes seconds.',
      stats: [
        { label: 'Rollback time',   value: 'seconds' },
        { label: 'Change tracking', value: 'forever' },
      ],
    },
    {
      id:            'cicd',
      title:         'CI/CD Pipeline',
      icon:          '🔄',
      color:         '#8b5cf6',
      animationType: 'pipeline',
      summary:       'Automates build, test, and deploy — no manual steps, no human errors',
      detail:        'A push to the main branch triggers the pipeline: code is compiled, tests run, a container image is built, and the new version deploys automatically. If any test fails, the pipeline stops — nothing broken reaches users. Teams with good CI/CD ship dozens of times a day.',
      stats: [
        { label: 'Test run',   value: '1–10 min' },
        { label: 'On failure', value: 'blocked' },
      ],
    },
    {
      id:            'frontend',
      title:         'Frontend (Client)',
      icon:          '💻',
      color:         '#06b6d4',
      animationType: 'cdn',
      summary:       "The app running in the user's browser — served globally by a CDN",
      detail:        'The frontend is a JavaScript app (React, Vue, or plain JS) that runs in the browser. The initial bundle is served by a CDN from a server close to the user — fast regardless of where your backend lives. Once loaded, the app makes API calls to your backend for dynamic data.',
      stats: [
        { label: 'CDN latency', value: '<10 ms' },
        { label: 'Runs on',     value: 'browser' },
      ],
    },
    {
      id:            'lb',
      title:         'Load Balancer',
      icon:          '⚖️',
      color:         '#0ea5e9',
      animationType: 'loadbalancer',
      summary:       'The front door — distributes requests across servers, routes around failures',
      detail:        'Every API request hits the load balancer first. It forwards each to a healthy backend server, spreading traffic evenly. It continuously health-checks every server — if one goes down, traffic is rerouted instantly. Adding a server is automatic: the load balancer starts including it right away.',
      stats: [
        { label: 'Health check', value: 'every 5 s' },
        { label: 'Failover',     value: 'automatic' },
      ],
    },
    {
      id:            'server',
      title:         'Application Server',
      icon:          '🖥️',
      color:         '#3b82f6',
      animationType: 'serverpulse',
      summary:       'Runs the business logic — stateless and horizontally scalable',
      detail:        'The server receives a request, runs your application code, and returns a response. The critical rule: servers must be stateless — no user sessions, no in-memory state. All shared data lives in the cache or database. This means any server can handle any request, and scaling is simply running more copies.',
      stats: [
        { label: 'Stateless',     value: 'required' },
        { label: 'Response time', value: '10–200 ms' },
      ],
    },
    {
      id:            'cache',
      title:         'Cache (Redis)',
      icon:          '⚡',
      color:         '#10b981',
      animationType: 'cache',
      summary:       'In-memory store — returns frequently-read data without hitting the database',
      detail:        'Redis sits between the server and the database. On a cache hit the data returns in under a millisecond. On a miss the server queries the database and stores the result. A well-tuned cache hits 90%+ of the time, meaning the database only sees 10% of read traffic.',
      stats: [
        { label: 'Latency',    value: '<1 ms' },
        { label: 'Hit target', value: '>90%' },
      ],
    },
    {
      id:            'db',
      title:         'Database',
      icon:          '🗄️',
      color:         '#f59e0b',
      animationType: 'database',
      summary:       'The permanent source of truth — every write ends up here',
      detail:        'The database stores every user, order, post, and transaction durably. Slower than the cache but the ground truth. Reads are served from cache when possible. Writes go directly to the database so nothing is ever lost.',
      stats: [
        { label: 'Read latency',  value: '1–10 ms' },
        { label: 'Write latency', value: '1–20 ms' },
        { label: 'Persistent',    value: 'yes' },
      ],
    },
    {
      id:            'monitor',
      title:         'Monitoring & Alerts',
      icon:          '📊',
      color:         '#f43f5e',
      animationType: 'monitor',
      summary:       'Logs, metrics, and alerts — tells you what your system is doing right now',
      detail:        'Every request is logged. Every error is captured. Latency, error rate, CPU, and memory are graphed in real time. When something crosses a threshold, an alert fires and the on-call engineer is paged. Production without monitoring is flying blind.',
      stats: [
        { label: 'Alert response', value: '<5 min' },
        { label: 'Log retention',  value: '30–90 days' },
      ],
    },
  ],
}
