export function buildConsistencyPatternsSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      consistency: null,
      message:     'Consistency Patterns: what guarantee does a read have about write visibility?',
      detail:      'Consistency patterns describe when a write becomes visible to subsequent readers across a distributed system. Strong consistency means every reader immediately sees the latest write from any node. Eventual consistency means readers converge to the same value over time. Most systems tune consistency per-query — paying the latency cost only where correctness is critical.',
    },
    {
      type:        'strong',
      activeNodes: ['writer', 'primary', 'replica-a', 'replica-b'],
      connections: { 'writer-primary': 'request', 'primary-ra': 'request', 'primary-rb': 'request' },
      consistency: 'strong',
      message:     'Strong consistency: write waits for quorum confirmation before acknowledging',
      detail:      'The writer sends x=1 to the primary. The primary replicates to a quorum of replicas (typically majority) and waits for their acknowledgment before replying success to the writer. Any subsequent read from any node in the quorum is guaranteed to return x=1. Higher latency (multiple round trips), but no stale reads ever. Used for financial balances, distributed locks, configuration stores.',
    },
    {
      type:        'strong-read',
      activeNodes: ['writer', 'primary'],
      connections: { 'writer-primary': 'both' },
      consistency: 'strong',
      message:     'Strong read: every reader sees the latest committed write, regardless of replica',
      detail:      'After the quorum write completes, any node in the system can serve the read and will return the correct value. ZooKeeper and etcd implement this via Raft — only the leader serves reads, and only after confirming it is still the leader. Cassandra achieves it by reading from a quorum of replicas and returning the value with the highest timestamp.',
    },
    {
      type:        'eventual',
      activeNodes: ['writer', 'primary', 'replica-a'],
      connections: { 'writer-primary': 'request', 'primary-ra': 'request' },
      consistency: 'eventual',
      message:     'Eventual consistency: write acknowledged immediately, replicas sync asynchronously',
      detail:      'The writer sends x=1 to the primary. The primary acknowledges immediately — no waiting for replicas. Replicas receive the update asynchronously within milliseconds to seconds. A reader hitting Replica B during this window sees the old value. This is the default in most NoSQL databases: DynamoDB (eventual reads), Cassandra (ONE consistency level), Redis replication. Fast writes, cheap reads, bounded staleness.',
    },
    {
      type:        'weak',
      activeNodes: ['writer', 'primary'],
      connections: { 'writer-primary': 'request' },
      consistency: 'weak',
      message:     'Weak consistency: no guarantee when (or if) a write becomes visible to readers',
      detail:      'Weak consistency makes no timing commitment. After a write, there is no guarantee subsequent reads will see it — the system makes a best-effort attempt. Used for real-time gaming state (a player\'s position 100ms ago is irrelevant), VoIP call data, and live video streams. The data expires before staleness matters. Never use weak consistency for anything a user can directly observe and compare.',
    },
    {
      type:        'read-your-writes',
      activeNodes: ['writer', 'primary', 'replica-a'],
      connections: { 'writer-primary': 'both', 'primary-ra': 'request' },
      consistency: 'read-your-writes',
      message:     'Read-your-writes: a user always sees their own most recent writes immediately',
      detail:      'After writing, the same user\'s subsequent reads are routed to the primary (or the same replica that received the write) until replication catches up. This prevents the jarring experience of posting a comment and immediately not seeing it. Implemented via sticky sessions, write tokens, or read-after-write headers. This is the minimum consistency guarantee most users unconsciously expect.',
    },
    {
      type:        'monotonic-reads',
      activeNodes: ['writer', 'replica-a', 'replica-b'],
      connections: { 'primary-ra': 'both', 'primary-rb': 'request' },
      consistency: 'monotonic-reads',
      message:     'Monotonic reads: once you\'ve seen version V, you never see an older version',
      detail:      'Without monotonic reads, a user can see a post appear (read from a fast replica), then disappear on refresh (read from a lagging replica) — the replication lag between two replicas causes a time-travel effect. With monotonic reads, once you\'ve seen data at version V, all subsequent reads return at least version V. Implemented by tracking the highest replication timestamp seen in the session and routing reads to replicas that have caught up.',
    },
    {
      type:        'causal',
      activeNodes: ['writer', 'primary', 'replica-a', 'replica-b'],
      connections: { 'writer-primary': 'request', 'primary-ra': 'both', 'primary-rb': 'both' },
      consistency: 'causal',
      message:     'Causal consistency: causally related writes appear in order to all readers',
      detail:      'A reply to a post must be seen after the post — the reply is causally dependent on the post. Causal consistency guarantees that causally related events (A happened-before B) appear in that order on all nodes. Causally independent events may appear in any order. Weaker than strong consistency but stronger than eventual — it captures the most important ordering guarantees for social applications without the quorum latency cost.',
    },
    {
      type:        'session',
      activeNodes: ['writer', 'primary', 'replica-a'],
      connections: { 'writer-primary': 'both', 'primary-ra': 'both' },
      consistency: 'session',
      message:     'Session consistency: read-your-writes + monotonic reads within a session',
      detail:      'Session consistency combines read-your-writes and monotonic reads — the practical baseline for most web applications. Within a single user session, you always see your own writes and you never see older state than you\'ve seen before. Different sessions may see different states. Most production systems target session consistency as the minimum acceptable guarantee for any user-facing feature.',
    },
    {
      type:        'trade-offs',
      activeNodes: ['writer', 'primary', 'replica-a', 'replica-b'],
      connections: { 'writer-primary': 'both', 'primary-ra': 'both', 'primary-rb': 'both' },
      consistency: null,
      message:     'Choosing a consistency level: match the model to the operation, not the service',
      detail:      'Apply different consistency levels to different operations within the same service. Use strong consistency for balance reads, idempotency key lookups, and distributed lock acquisition. Use read-your-writes for profile updates the same user immediately re-reads. Use eventual consistency for activity feeds, recommendation counters, and analytics dashboards. Cassandra and DynamoDB expose this as a per-query setting — you pay the latency cost only where it is justified.',
    },
  ]
}
