export default {
  id:          'reshaded',
  type:        'concept',
  title:       'The RESHADED Framework',
  category:    'framework',
  tags:        ['reshaded', 'interview-framework', 'requirements', 'estimation', 'high-level-design', 'api-design', 'detailed-design', 'trade-offs', 'interview-strategy'],
  description: 'A fixed eight-step checklist for running a system design interview end to end: Requirements, Estimation, Storage schema, High-level design, API design, Detailed design, Evaluate for bottlenecks, and Discuss trade-offs. The value isn\'t novelty — it\'s that following the same order every time means nothing gets skipped under interview pressure, and the interviewer always knows which phase you\'re in.',
  metaphor:    "A pilot's pre-flight checklist. A pilot doesn't improvise a new sequence for every flight — they run the same checklist whether it's a puddle-jumper or a 747, because the checklist is what prevents a skipped step from becoming a mid-air surprise. RESHADED is the same idea applied to a 45-minute design interview: the destination (URL shortener vs. Uber) changes, the checklist doesn't.",
  path:        '/system-design/reshaded',
  howItWorks: [
    'R — Requirements: Before proposing anything, pin down what the system must do (functional) and how well it must do it (non-functional: availability, latency, consistency). Explicitly ask what\'s out of scope — an interviewer who says "handle payments" but doesn\'t mention refunds is telling you refunds are out of scope, not that you should guess. This maps directly to the `requirements: { functional, nonFunctional, scale, outOfScope }` block on every design in this app.',
    'E — Estimation: Convert the requirements into numbers — QPS (reads and writes separately), storage growth over 1–5 years, bandwidth, and cache size. These numbers are what justify every later decision: "we need a cache" is an opinion, "read QPS is 1000x write QPS so a 5 GB Redis cache absorbs 80% of reads" is an argument. Skipping this step is the single most common reason a design conversation goes in circles later.',
    'S — Storage Schema: Sketch the core entities and their fields before drawing a single box on the whiteboard. Decide SQL vs. NoSQL here, driven by the access patterns implied by the requirements (is this read-heavy point lookups, or write-heavy with flexible schema?) — not by familiarity. This is the `dataModel: [{ entity, fields }]` section of each design.',
    'H — High-Level Design: Draw the smallest set of boxes that satisfies the functional requirements — client, one or two services, one datastore. Resist the urge to add Kafka, Redis, and five microservices in the first pass; high-level design is deliberately the "walking skeleton," refined in the next two steps. This is `hldFlows` — and the best answers build it in stages (v1 does the bare minimum, v2 adds caching, v3 adds the harder feature), not as one finished diagram.',
    'A — API Design: Define the concrete request/response contract for each functional requirement — HTTP method, path, request body, response body, status codes. This is where vague requirements get caught: if you can\'t write the endpoint, the requirement wasn\'t actually clear. Maps to `apiDesign: [{ method, path, reqBody, resBody }]`.',
    'D — Detailed Design: Go deep on the two or three hardest sub-problems the requirements actually demand — e.g. for a URL shortener, how IDs are generated uniquely without coordination; for a chat system, how message ordering survives out-of-order delivery. This is where seniority shows: a mid-level candidate names one valid approach, a senior candidate compares two or three with real trade-offs.',
    'E — Evaluate: Step back and pressure-test your own design. Where\'s the single point of failure? What happens when the database goes down, the cache is cold, or traffic 10x\'s overnight? A good interviewer wants to see you find your own weak points before they have to point them out.',
    'D — Discuss: Talk explicitly about what you\'d do differently at a different scale, what you deliberately left out of scope and why, and what monitoring/alerting would tell you the system is unhealthy in production. This is the difference between "I designed a system" and "I designed a system I understand the limits of."',
  ],
  keyPoints: [
    'RESHADED is a fixed order, not a suggestion — Requirements → Estimation → Storage Schema → High-Level Design → API Design → Detailed Design → Evaluate → Discuss. Running the letters out of order (especially jumping straight to High-Level Design) is the #1 way candidates lose the thread',
    'Requirements and Estimation together should take ~15–20% of a 45-minute interview — rushing them is the most common mid-level mistake, because every later decision needs to cite one of these numbers to sound justified rather than arbitrary',
    'Every design in this app is literally structured as RESHADED: requirements → dataModel → apiDesign → hldFlows → deepDive → levelExpectations — reading any flagship design here is reading a worked RESHADED answer',
    'High-Level Design should be a "walking skeleton" first (client → one service → one datastore), then built up in stages during Detailed Design — not one fully-loaded diagram with a message queue, cache, and CDN before the basic read/write path even exists',
    'Detailed Design is where levelling happens: naming one valid approach to a hard sub-problem is mid-level; comparing 2–3 approaches with concrete trade-offs is senior; reasoning about coordination across regions/failure domains is staff',
    'Evaluate and Discuss are frequently skipped when time runs short — but explicitly naming your own single points of failure and what you left out of scope is often worth more signal than another 5 minutes of box-drawing',
  ],
  components: [
    {
      id:            'requirements',
      title:         'R — Requirements',
      icon:          '📋',
      color:         '#f59e0b',
      animationType: 'checklist',
      summary: 'Functional scope + non-functional targets, and what\'s explicitly out of scope',
      detail:  'Ask clarifying questions until you can state, in one sentence each, what the system does (functional) and how well it must do it (availability/latency/consistency targets). Then ask what\'s out of scope — interviewers expect this question and it prevents you from over-building.',
      stats: [
        { label: 'Time budget', value: '~5 min' },
        { label: 'Output',      value: 'functional + non-functional list' },
        { label: 'Common miss', value: 'Not asking what\'s out of scope' },
      ],
    },
    {
      id:            'estimation',
      title:         'E — Estimation',
      icon:          '🧮',
      color:         '#f97316',
      animationType: 'throughput',
      summary: 'Turn requirements into QPS, storage, and bandwidth numbers',
      detail:  'DAU × actions/day → QPS; apply a 5–10× peak multiplier. Payload size × write volume × retention → storage. These numbers are the justification for every architectural choice that follows — "why a cache" is answered by a read:write ratio, not intuition.',
      stats: [
        { label: 'Time budget', value: '~5 min' },
        { label: 'Peak multiplier', value: '5–10×' },
        { label: 'Output',      value: 'QPS, storage/yr, bandwidth' },
      ],
    },
    {
      id:            'storage-schema',
      title:         'S — Storage Schema',
      icon:          '🗄️',
      color:         '#06b6d4',
      animationType: 'schema',
      summary: 'Core entities and fields, and the SQL vs. NoSQL call',
      detail:  'Sketch entities and their fields before boxes-and-arrows. The access pattern implied by the requirements — point lookups vs. flexible/nested data, read-heavy vs. write-heavy — should drive the SQL/NoSQL decision, not prior familiarity with one or the other.',
      stats: [
        { label: 'Time budget', value: '~5 min' },
        { label: 'Decides',     value: 'SQL vs. NoSQL' },
        { label: 'Output',      value: 'entity/field list' },
      ],
    },
    {
      id:            'high-level-design',
      title:         'H — High-Level Design',
      icon:          '🏗️',
      color:         '#3b82f6',
      animationType: 'boxes',
      summary: 'The smallest diagram that satisfies the functional requirements',
      detail:  'Draw a walking skeleton — client, one or two services, one datastore — before adding caches, queues, or CDNs. Build it up in versions (v1 → v2 → v3) during Detailed Design rather than presenting the fully-loaded architecture up front.',
      stats: [
        { label: 'Time budget', value: '~10 min' },
        { label: 'Anti-pattern', value: 'Kafka + Redis in v1' },
        { label: 'Output',      value: 'v1 walking skeleton' },
      ],
    },
    {
      id:            'api-design',
      title:         'A — API Design',
      icon:          '🔌',
      color:         '#0ea5e9',
      animationType: 'endpoint',
      summary: 'Concrete request/response contracts for each functional requirement',
      detail:  'Write the method, path, request body, and response body for every requirement from step R. If you can\'t write the endpoint cleanly, the requirement wasn\'t actually clear — this step catches ambiguity that survives the requirements pass.',
      stats: [
        { label: 'Time budget', value: '~5 min' },
        { label: 'Format',      value: 'method + path + body' },
        { label: 'Catches',     value: 'Ambiguous requirements' },
      ],
    },
    {
      id:            'detailed-design',
      title:         'D — Detailed Design',
      icon:          '🔬',
      color:         '#8b5cf6',
      animationType: 'deepdive',
      summary: 'Go deep on the 2–3 sub-problems the requirements actually demand',
      detail:  'This is where levelling happens. Naming one valid approach to the hardest sub-problem (e.g. unique ID generation) is mid-level signal; comparing multiple approaches with concrete trade-offs is senior signal; reasoning about cross-region coordination is staff signal.',
      stats: [
        { label: 'Time budget', value: '~10 min' },
        { label: 'Signal',      value: 'Where levelling happens' },
        { label: 'Output',      value: '2–3 deep sub-problems' },
      ],
    },
    {
      id:            'evaluate',
      title:         'E — Evaluate',
      icon:          '🔍',
      color:         '#f43f5e',
      animationType: 'monitor',
      summary: 'Pressure-test your own design for single points of failure',
      detail:  'Ask yourself the questions the interviewer would: what breaks if the database goes down, the cache is cold, or traffic spikes 10×? Finding your own weak points first is stronger signal than a design that has no acknowledged weaknesses.',
      stats: [
        { label: 'Time budget', value: '~3 min' },
        { label: 'Looks for',   value: 'Single points of failure' },
        { label: 'Signal',      value: 'Self-critique' },
      ],
    },
    {
      id:            'discuss',
      title:         'D — Discuss',
      icon:          '💬',
      color:         '#10b981',
      animationType: 'chat',
      summary: 'Trade-offs, what\'s out of scope, and how you\'d know it\'s unhealthy in prod',
      detail:  'Name what you\'d do differently at 10× or 100× scale, restate what you deliberately left out and why, and describe what monitoring/alerting would tell you the system is failing. This closes the loop back to Requirements\' out-of-scope list.',
      stats: [
        { label: 'Time budget', value: '~2 min' },
        { label: 'Closes loop with', value: 'Requirements (out of scope)' },
        { label: 'Signal',      value: 'Production awareness' },
      ],
    },
  ],
}
