export function buildMessageQueuesSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      queueDepth:  0,
      message:     'Message Queues: async decoupling between producers and consumers',
      detail:      'A message queue sits between a producer (the service that generates work) and consumers (the services that process it). The producer publishes a message and returns immediately — it does not wait for processing. Consumers read at their own pace. This async decoupling enables load leveling across traffic spikes, fault isolation, and independent scaling of producers and consumers.',
    },
    {
      type:        'sync-problem',
      activeNodes: ['producer', 'consumer-a'],
      connections: { 'producer-queue': 'request' },
      queueDepth:  0,
      message:     'Synchronous coupling: producer waits for consumer — both fail together',
      detail:      'Without a queue, the producer calls the consumer synchronously and waits for a response. If the consumer is slow, the producer blocks. If the consumer crashes, the producer fails too. During traffic spikes, the consumer is overwhelmed and the producer backs up. Services are tightly coupled — you cannot deploy, scale, or fail one without affecting the other.',
    },
    {
      type:        'publish',
      activeNodes: ['producer', 'queue'],
      connections: { 'producer-queue': 'request' },
      queueDepth:  1,
      message:     'Producer publishes a message to the queue and returns immediately',
      detail:      'The producer sends a message (payload + metadata: message ID, timestamp, correlation ID, priority) to the queue and receives an immediate acknowledgment. The producer does not know which consumer will process the message, when it will be processed, or whether it succeeded. This is the fundamental decoupling: the producer\'s work is done the moment the queue confirms receipt.',
    },
    {
      type:        'persist',
      activeNodes: ['queue'],
      connections: {},
      queueDepth:  3,
      message:     'Queue persists messages durably — consumers can be offline',
      detail:      'The queue stores messages on disk (Kafka, RabbitMQ) or in a distributed data store (SQS). Messages survive broker restarts and consumer outages. If both consumers are down for maintenance, messages accumulate in the queue. When consumers come back online, they process the backlog in order. Kafka retains messages for days or weeks — consumers can replay the entire history to rebuild any projection.',
    },
    {
      type:        'consume',
      activeNodes: ['queue', 'consumer-a', 'consumer-b'],
      connections: { 'queue-ca': 'request', 'queue-cb': 'request' },
      queueDepth:  2,
      message:     'Consumers pull messages and must acknowledge before the queue removes them',
      detail:      'Each consumer polls the queue or receives a push. The queue holds the message as "in-flight" until the consumer explicitly acknowledges receipt (ACK). If the consumer crashes before sending the ACK, the message becomes visible again after a visibility timeout and is redelivered. This at-least-once delivery guarantee means consumers must be idempotent — processing the same message twice must produce the same outcome as processing it once.',
    },
    {
      type:        'backpressure',
      activeNodes: ['producer', 'queue', 'consumer-a'],
      connections: { 'producer-queue': 'request', 'queue-ca': 'request' },
      queueDepth:  5,
      message:     'Backpressure absorption: queue grows during spikes, consumers drain the backlog',
      detail:      'Producers send 10,000 messages/second. Consumers process 1,000/second. Without a queue this means 9,000 dropped requests per second. With a queue, messages accumulate and consumers drain the backlog when load subsides. Monitor queue depth as a leading indicator of processing lag — a growing queue means consumers are falling behind and you need to scale consumer instances horizontally.',
    },
    {
      type:        'dlq',
      activeNodes: ['queue', 'consumer-a'],
      connections: { 'queue-ca': 'request', 'queue-dlq': 'request' },
      queueDepth:  2,
      message:     'Dead Letter Queue: failed messages are quarantined after N retry attempts',
      detail:      'A message that consistently fails processing (malformed payload, permanent business error) is moved to the Dead Letter Queue after N delivery attempts. The DLQ captures it for manual inspection, alerting, and replay after the bug is fixed. Without a DLQ, a single "poison pill" message cycles in the queue forever, blocking all consumers from making progress on subsequent messages.',
    },
    {
      type:        'pubsub',
      activeNodes: ['producer', 'queue', 'consumer-a', 'consumer-b'],
      connections: { 'producer-queue': 'request', 'queue-ca': 'request', 'queue-cb': 'request' },
      queueDepth:  1,
      message:     'Pub/Sub: one publisher, multiple independent consumer groups',
      detail:      'Kafka implements pub/sub with topics and consumer groups. Each consumer group gets its own independent copy of every message. One group sends confirmation emails, another writes to a data warehouse, another triggers push notifications — all from the same event stream. Adding a new consumer group requires zero changes to the producer. Point-to-point queues (SQS) deliver each message to exactly one consumer — use this when you want competing consumers scaling horizontally on the same work.',
    },
    {
      type:        'delivery-guarantees',
      activeNodes: ['producer', 'queue', 'consumer-a'],
      connections: { 'producer-queue': 'both', 'queue-ca': 'both' },
      queueDepth:  0,
      message:     'Delivery guarantees: at-least-once vs exactly-once vs at-most-once',
      detail:      'At-least-once (default): messages are never lost but may be delivered multiple times. Consumers must be idempotent. At-most-once: messages are delivered at most once — if the consumer crashes before ACKing, the message is lost. Used for metrics where occasional loss is acceptable. Exactly-once: theoretically achievable with Kafka transactions, but expensive. In practice, design consumers to be idempotent and accept at-least-once delivery — simpler, faster, equally correct.',
    },
    {
      type:        'full-system',
      activeNodes: ['producer', 'queue', 'consumer-a', 'consumer-b'],
      connections: { 'producer-queue': 'request', 'queue-ca': 'both', 'queue-cb': 'both', 'queue-dlq': 'request' },
      queueDepth:  2,
      message:     'Full message queue system: async, resilient, independently scalable',
      detail:      'Producers publish and move on. The queue durably buffers messages, absorbs spikes, and delivers to consumers at their pace. At-least-once delivery with consumer idempotency ensures correctness. Dead letter queues capture failures. Consumer groups enable pub/sub fan-out. Independent scaling means you can add consumers during a traffic surge without touching the producer. This is the standard pattern for email delivery, image processing, report generation, and data pipeline ingestion.',
    },
  ]
}
