export default {
  id:          'design-requirements',
  type:        'concept',
  title:       'Design Requirements',
  category:    'requirements',
  tags:        ['requirements', 'scalability', 'availability', 'reliability', 'redundancy', 'throughput', 'latency', 'sla', 'slo', 'fault-tolerance'],
  description: 'Every distributed system reduces to three problems: moving data across a network, storing it in the right place, and transforming it into something useful. Design requirements are the measurable targets — availability, reliability, throughput, and latency — that tell you whether your solution to those three problems is actually good enough.',
  metaphor:    "A city's water system: the pipes move water (data movement), the reservoir stores it (data storage), and the treatment plant transforms it into drinking water (data transformation). The system quality requirements — pressure, purity, uptime — are the design requirements. Dig the pipes first, engineer to spec second.",
  path:        '/system-design/design-requirements',
  howItWorks: [
    'Frame every design as three sub-problems: moving data (network, queues, CDNs), storing data (databases, blob stores, distributed file systems), and transforming data (stream processors, batch jobs, aggregations). Every architectural decision maps to one of these three.',
    'Collect availability requirements first — they cascade into everything else. "Five nines" (99.999%) demands redundant hardware, automated failover, and zero-downtime deployments. "Three nines" (99.9%) does not. Establish the target before picking any technology.',
    'Distinguish reliability from availability: availability measures whether the system is up; reliability measures whether individual requests succeed. A system can be available but unreliable under load spikes or DDoS. Fault tolerance — the system detecting and recovering from failures — bridges the gap.',
    'Design redundancy to match the reliability target. Active-passive redundancy keeps a hot standby that promotes on failure; active-active redundancy keeps all nodes serving live traffic so losing one just reduces capacity rather than causing an outage.',
    'Estimate throughput before sizing infrastructure: multiply daily active users by average requests per session to get QPS, then apply a peak multiplier (typically 5–10×). Derive storage from payload size × daily write volume. These numbers determine your horizontal scaling needs before a single server is provisioned.',
    'Set explicit latency budgets at p50 and p99 — never just the average. In a system handling 1M requests per day, p99 affects 10,000 users. Codify targets as SLOs internally ("p99 < 200ms") and SLAs externally ("99.99% monthly uptime or service credits apply"). Every architecture choice — replication, caching, CDN placement — must be traceable to one of these targets.',
  ],
  keyPoints: [
    'All system design reduces to three primitives: move data, store data, transform data — every component serves one of these three roles',
    'Availability = uptime / (uptime + downtime). 99% = 3.65 days of outage per year; 99.999% = 5 minutes. Each additional nine costs significantly more',
    'Active-active redundancy is stronger than active-passive: both nodes serve live traffic, so losing one reduces capacity rather than triggering a failover',
    'Throughput is measured in QPS for user-facing APIs and bytes/second for data pipelines — vertical scaling has a ceiling, horizontal scaling does not',
    'Always specify latency at p99, not just the median. A p99 more than 10× the p50 signals a long-tail problem that the average completely hides',
    'SLOs are internal targets; SLAs are external contracts with financial penalties. Design to the SLA — not the other way around',
  ],
}
