export function buildAvailabilityPatternsSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      failState:   null,
      message:     'Availability Patterns: keeping systems up despite failures',
      detail:      'High availability requires redundancy (duplicate components), automated failover (promotion when a primary fails), circuit breaking (stopping cascading failures), and graceful degradation (serving reduced functionality rather than returning errors). The combination of these patterns determines your system\'s practical uptime.',
    },
    {
      type:        'active-active',
      activeNodes: ['lb', 'primary', 'standby', 'client'],
      connections: { 'client-lb': 'request', 'lb-primary': 'both', 'lb-standby': 'both', 'primary-standby': 'both' },
      failState:   null,
      message:     'Active-Active: both servers handle live traffic simultaneously',
      detail:      'In active-active, both Primary and Standby are live. The load balancer distributes requests across both. If one fails, the other absorbs all traffic immediately — no failover delay. This provides maximum throughput and the fastest failure response. The trade-off: both nodes must handle concurrent writes, introducing consistency complexity that active-passive avoids.',
    },
    {
      type:        'active-passive',
      activeNodes: ['lb', 'primary', 'client'],
      connections: { 'client-lb': 'request', 'lb-primary': 'both', 'primary-standby': 'request' },
      failState:   null,
      message:     'Active-Passive: primary handles traffic, standby stays synchronized and ready',
      detail:      'In active-passive, the primary handles all traffic. The standby continuously replicates data from the primary but serves no requests. When the primary fails, the standby is promoted. Failover takes 30–120 seconds (health check interval + promotion + DNS/load balancer update). Users may see a brief outage. Simpler to reason about than active-active because only one node writes at a time.',
    },
    {
      type:        'health-check',
      activeNodes: ['lb', 'primary'],
      connections: { 'lb-primary': 'request' },
      failState:   null,
      message:     'Health checks: load balancer probes each node every few seconds',
      detail:      'The load balancer sends HTTP GET /health (or TCP ping) to each server on a configurable interval (typically 5–30 seconds). A node that fails to respond within the timeout is marked unhealthy and removed from rotation. After recovery, nodes must pass a defined number of consecutive health checks before being re-added — the warmup window prevents a cold-cache node from immediately receiving production traffic.',
    },
    {
      type:        'primary-fail',
      activeNodes: ['lb', 'standby'],
      connections: { 'lb-standby': 'request' },
      failState:   'primary-down',
      message:     'Primary fails: load balancer detects failure and promotes standby',
      detail:      'The health check to Primary times out after two consecutive failures (configurable). The load balancer removes Primary from rotation and routes all traffic to Standby. Standby is promoted to primary role. DNS or load balancer config is updated to point at the new primary. The promotion process and replication lag between the point of failure and the last sync determines the Recovery Point Objective (RPO).',
    },
    {
      type:        'circuit-breaker',
      activeNodes: ['lb', 'primary'],
      connections: { 'client-lb': 'request', 'lb-primary': 'response' },
      failState:   'circuit-open',
      message:     'Circuit Breaker: trips open when downstream dependency starts failing',
      detail:      'The circuit breaker wraps calls to a downstream service. When the error rate exceeds a threshold, the circuit "trips" to the open state — subsequent calls immediately return a cached fallback without attempting the real call. After a timeout, the circuit enters half-open state and sends one probe request. Success closes the circuit; failure reopens it. This prevents one slow service from cascading timeouts across every upstream caller.',
    },
    {
      type:        'retry',
      activeNodes: ['client', 'lb'],
      connections: { 'client-lb': 'both' },
      failState:   null,
      message:     'Retry with exponential backoff and jitter: handle transient failures safely',
      detail:      'Transient failures (brief network hiccup, momentary overload) can be retried. Each retry waits 2× longer than the last (exponential backoff), plus a small random delay (jitter). Without jitter, all retrying clients synchronize their retries, creating a thundering herd that amplifies the original overload. Formula: delay = min(cap, base × 2^attempt) + random(0, jitter). Jitter distributes the load across the recovery window.',
    },
    {
      type:        'graceful-degradation',
      activeNodes: ['lb', 'primary', 'client'],
      connections: { 'client-lb': 'request', 'lb-primary': 'response' },
      failState:   'degraded',
      message:     'Graceful degradation: serve reduced but useful functionality when a dependency fails',
      detail:      'Design every feature with a degraded mode: a product page can display without recommendations if the ML service is down. A search page can show cached results if the search cluster is overloaded. An article can render without comments if the comments service is slow. Showing a partial page with a notice is always better than a 500 error. Design degradation modes before they become a 3am production question.',
    },
    {
      type:        'full-system',
      activeNodes: ['client', 'lb', 'primary', 'standby'],
      connections: { 'client-lb': 'both', 'lb-primary': 'both', 'lb-standby': 'request', 'primary-standby': 'both' },
      failState:   null,
      message:     'Full availability stack: redundancy + failover + health checks + circuit breakers',
      detail:      'Production high-availability combines all patterns: active-active or active-passive redundancy eliminates single points of failure. Automated health checks detect failures in seconds. Circuit breakers prevent cascading failures across service boundaries. Retry with jitter handles transient errors. Graceful degradation ensures users always see something useful. Each layer adds another 9 to your uptime SLA.',
    },
  ]
}
