export function buildCapTheoremSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      partition:   false,
      capChoice:   null,
      message:     'CAP Theorem: a distributed system can guarantee at most 2 of 3 properties',
      detail:      'Consistency (every read reflects the most recent write), Availability (every request gets a non-error response), Partition Tolerance (the system keeps operating despite network splits). Because network partitions are unavoidable in real distributed systems, the practical choice is always CP vs AP — never CA at scale.',
    },
    {
      type:        'healthy',
      activeNodes: ['node-a', 'node-b', 'client'],
      connections: { 'client-a': 'both', 'a-b': 'both' },
      partition:   false,
      capChoice:   null,
      message:     'Healthy state: all nodes connected, writes replicate immediately',
      detail:      'No partition. Node A and Node B are fully synchronized — every write to A is immediately replicated to B. Any client reading from either node gets the same value. When the network is healthy, achieving all three CAP properties simultaneously is trivial. CAP only forces a trade-off when a partition actually occurs.',
    },
    {
      type:        'write',
      activeNodes: ['client', 'node-a'],
      connections: { 'client-a': 'request' },
      partition:   false,
      capChoice:   null,
      message:     'Client writes x=1 to Node A — replicates to Node B',
      detail:      'The client writes x=1 to Node A. Node A replicates the write to Node B before acknowledging. Both nodes now agree x=1. A subsequent read from either node returns the correct value. This is normal operation — CAP trade-offs are invisible until the network fails.',
    },
    {
      type:        'partition',
      activeNodes: ['node-a', 'node-b'],
      connections: {},
      partition:   true,
      capChoice:   null,
      message:     'Network partition: A and B can no longer communicate',
      detail:      'A network partition splits the cluster. Node A and Node B cannot exchange messages. Writes to Node A cannot be replicated to Node B, and vice versa. Now the system must choose: refuse requests to stay consistent (CP), or continue serving requests with potentially stale data (AP). There is no third option.',
    },
    {
      type:        'cp',
      activeNodes: ['client', 'node-a'],
      connections: { 'client-a': 'response' },
      partition:   true,
      capChoice:   'CP',
      message:     'CP choice: Node A refuses writes, returns error to maintain consistency',
      detail:      'A CP system chooses consistency over availability during a partition. Node A detects it cannot reach Node B, so it refuses to accept writes (and possibly reads) until the partition heals. Clients receive errors or timeouts. Examples: ZooKeeper, etcd, HBase. Best for leader election, distributed locks, configuration stores — where a stale read causes real harm.',
    },
    {
      type:        'ap',
      activeNodes: ['client', 'node-a', 'node-b'],
      connections: { 'client-a': 'request' },
      partition:   true,
      capChoice:   'AP',
      message:     'AP choice: both nodes keep serving, writes diverge during partition',
      detail:      'An AP system chooses availability over consistency during a partition. Both Node A and Node B continue accepting writes independently. When the partition heals, the system resolves conflicts — via last-write-wins, vector clocks, or application-level merge logic. Examples: DynamoDB, Cassandra, CouchDB. Best for shopping carts, social feeds, user preferences.',
    },
    {
      type:        'heal',
      activeNodes: ['node-a', 'node-b'],
      connections: { 'a-b': 'both' },
      partition:   false,
      capChoice:   'AP',
      message:     'Partition heals: AP nodes reconcile diverged writes',
      detail:      'The network partition heals and both nodes synchronize. In an AP system, diverged writes from both sides are now reconciled. Cassandra uses last-write-wins by timestamp. DynamoDB offers configurable merge. Riak uses vector clocks. The reconciliation strategy is determined at design time — teams must plan for conflict resolution before it becomes a production incident.',
    },
    {
      type:        'ca-myth',
      activeNodes: ['client', 'node-a'],
      connections: { 'client-a': 'both' },
      partition:   false,
      capChoice:   'CA',
      message:     'CA systems: only possible on a single node — not truly distributed',
      detail:      'A standalone PostgreSQL instance is CA (Consistent + Available), but it is not partition-tolerant because it is not distributed. Once you add a second node, network partitions become possible and you must choose CP or AP. "CA distributed system" is a contradiction in terms — the CA quadrant in CAP diagrams only applies to single-node setups.',
    },
    {
      type:        'pacelc',
      activeNodes: ['client', 'node-a', 'node-b'],
      connections: { 'client-a': 'request', 'a-b': 'both' },
      partition:   false,
      capChoice:   null,
      message:     'PACELC: even without a partition, every read trades latency vs consistency',
      detail:      'PACELC extends CAP: even with no partition (the E case), distributed systems trade off latency (L) vs consistency (C) on every request. Reading from your local replica is fast but may be stale. Waiting for quorum confirmation is consistent but slower. Cassandra\'s QUORUM reads are latency-consistent, ONE reads are latency-optimized. This trade-off exists on every single request — not just during failures.',
    },
    {
      type:        'examples',
      activeNodes: ['client', 'node-a', 'node-b'],
      connections: { 'client-a': 'both', 'a-b': 'both' },
      partition:   false,
      capChoice:   null,
      message:     'Real-world examples: matching the CAP model to the use case',
      detail:      'CP systems: ZooKeeper (leader election), etcd (Kubernetes config), HBase (strong reads). AP systems: DynamoDB (sessions, carts), Cassandra (time-series, activity feeds), CouchDB (offline-first). Most databases offer configurable consistency — Cassandra\'s consistency level is set per-query, letting you pay for stronger consistency only when needed.',
    },
  ]
}
