export default {
  id:          'abstractions-in-system-design',
  type:        'concept',
  title:       'Abstractions in System Design',
  category:    'framework',
  tags:        ['abstraction', 'interface', 'implementation', 'leaky-abstraction', 'libraries', 'frameworks', 'transactions', 'cloud-abstraction', 'network-abstraction', 'consistency-abstraction', 'failure-abstraction'],
  description: 'Abstraction is the technique of hiding complex details to focus on core goals. It manages the complexity of distributed systems by separating high-level design decisions from infrastructure concerns — letting teams build and scale applications without dealing with low-level details at every step. Naming an abstraction correctly, and knowing where it leaks, is what makes a design conversation move fast instead of getting stuck relitigating fundamentals.',
  metaphor:    "A car. From the curb, it's just \"a car\" — you recognize it, you could drive it, you can talk about it as a category without ever popping the hood. Open the hood, though, and you're staring at this exact engine's pistons, crankshaft, timing belt, and alternator — precisely machined, specific to this one vehicle. Study one piston's exact part number and tolerance closely enough, and you've lost the ability to talk about \"a car\" at all — you're now talking about one specific part of one specific engine. That trade-off — interface vs. internals — is the entire idea of abstraction, and the interactive diagram below walks through it directly. (The same idea shows up in Grokking's own illustration: picture \"a bird\" and you reason about the general category — flies, has feathers — not one sparrow's exact feather pattern.)",
  path:        '/system-design/abstractions-in-system-design',
  howItWorks: [
    'An abstraction is an interface (the promise) plus a hidden implementation (how the promise is kept) — "an at-least-once, ordered-per-partition queue" is a real abstraction; "a queue" is just a label. The cards below go deep on the specific abstractions system design leans on most; this section stays at the overview level.',
    'Abstractions leak when the hidden detail becomes impossible to ignore — a dropped TCP connection forces "did my write actually commit?" back into view. Every "Detailed Design" and "Evaluate" phase of RESHADED is really: find where your chosen abstraction leaks, and design for that leak explicitly, before the interviewer has to.',
    'Picking the right altitude to talk at is its own skill: explaining a TCP handshake when asked to design a chat system drowns the conversation; saying "we\'ll use a message queue" with nothing further is a label, not a design. Self-check for any box on your diagram — can you state in one sentence what it guarantees?',
  ],
  keyPoints: [
    'Abstraction = hiding complex detail to focus on core goals — the bird illustration: reason about the general category, not one instance\'s specific implementation, or you lose the ability to reason about the general concept at all',
    'Software engineering already runs on this: libraries and frameworks expose well-defined interfaces so you reuse tested functionality instead of rebuilding hardware or an OS from scratch — system design interviews extend the same habit to infrastructure',
    'Database transactions are the clean concrete example: commit-on-success / abort-on-failure hides all concurrent-access complexity behind a two-outcome interface, so developers reason about business logic, not concurrency',
    'Distributed architectures exist because modern apps must scale past single-node limits — cloud providers (AWS/GCP/Azure) sell managed services at varying abstraction levels specifically so teams scale without owning the infrastructure detail',
    'Abstractions leak under failure — a dropped TCP connection forces "did my write commit?" back into view. RESHADED\'s "Detailed Design" and "Evaluate" phases exist to find that leak before the interviewer does',
    'This app organizes around the three pillars this chapter actually covers — communication (RPC), data consistency (Consistency Models Spectrum), and failure (Failure Models Spectrum) — not an exhaustive list',
  ],
  components: [
    {
      id:            'general-abstraction',
      title:         'What Is Abstraction?',
      icon:          '🐦',
      color:         '#8b5cf6',
      animationType: 'abstraction',
      summary: 'Hiding unnecessary detail to reason about the general category, not one instance',
      detail:  'Picture "a bird" and you reason about the general category — flies, has feathers, lays eggs — not one sparrow\'s exact feather pattern. Fixate on one instance\'s unique details instead, and you lose the ability to discuss the general concept at all — the same failure mode as a design conversation that drops into implementation too early.',
      stats: [
        { label: 'Hides',    value: 'Instance-specific detail' },
        { label: 'Exposes',  value: 'The general category' },
        { label: 'Example',  value: 'A specific sparrow → "a bird"' },
      ],
    },
    {
      id:            'database-abstraction',
      title:         'Database Abstraction',
      icon:          '🗄️',
      color:         '#06b6d4',
      animationType: 'storage',
      summary: 'Transactions hide concurrent-access complexity behind commit / abort',
      detail:  'A transaction guarantees data moves between consistent states via a two-outcome interface: commit on success, abort on failure. That\'s the entire promise — the concurrency control underneath (locks, MVCC, WAL) stays hidden, so developers reason about business logic instead of concurrent access on every query.',
      stats: [
        { label: 'Hides',    value: 'Locks, MVCC, WAL' },
        { label: 'Exposes',  value: 'Commit / abort' },
        { label: 'Guarantees', value: 'Consistent state transitions' },
      ],
    },
    {
      id:            'network-abstraction',
      title:         'Network Abstraction',
      icon:          '🔌',
      color:         '#3b82f6',
      animationType: 'network',
      summary: 'How two machines agree to talk — hiding sockets, serialization, and retries',
      detail:  'RPC (and REST, as a specific style of it) is the abstraction that lets you say "call this function on that machine" without writing socket code. The interface question is always: is this call synchronous or async, and is it safe to retry (idempotent)? See the RPC concept.',
      stats: [
        { label: 'Hides',    value: 'Sockets, serialization' },
        { label: 'Exposes',  value: 'Sync/async, idempotency' },
        { label: 'See also', value: 'RPC' },
      ],
    },
    {
      id:            'consistency-abstraction',
      title:         'Consistency Abstraction',
      icon:          '🔄',
      color:         '#f43f5e',
      animationType: 'consistency',
      summary: 'What a reader can assume about a write\'s visibility — hiding replication and consensus',
      detail:  'Linearizable, sequential, causal, and eventual consistency are points on a spectrum trading recency guarantees for latency and availability. The implementation (Raft, Paxos, gossip, last-write-wins) is hidden behind whichever point on the spectrum you choose. See the Spectrum of Consistency Models.',
      stats: [
        { label: 'Hides',    value: 'Raft, Paxos, gossip' },
        { label: 'Exposes',  value: 'Recency guarantee' },
        { label: 'See also', value: 'Consistency Models Spectrum' },
      ],
    },
    {
      id:            'failure-abstraction',
      title:         'Failure Abstraction',
      icon:          '💥',
      color:         '#f59e0b',
      animationType: 'failure',
      summary: 'What ways a component can actually break — hiding the messy reality of hardware/software failure',
      detail:  'Fail-stop, crash-recovery, omission, and Byzantine are a spectrum of failure assumptions. Most interview-level design assumes fail-stop or crash-recovery; the assumed model directly drives how much redundancy and coordination the design needs. See the Spectrum of Failure Models.',
      stats: [
        { label: 'Hides',    value: 'Actual hardware/software faults' },
        { label: 'Exposes',  value: 'What redundancy must tolerate' },
        { label: 'See also', value: 'Failure Models Spectrum' },
      ],
    },
  ],
}
