export default {
  id:          'failure-models-spectrum',
  type:        'concept',
  title:       'Spectrum of Failure Models',
  category:    'framework',
  tags:        ['failure-model', 'fail-stop', 'crash-recovery', 'omission-failure', 'byzantine-failure', 'fault-tolerance', 'distributed-systems', 'consensus'],
  description: 'A taxonomy of the ways a component can actually fail, from easiest to detect and handle (fail-stop — it crashes and stays down) to hardest (Byzantine — it keeps running and reports results, but some of them are wrong or malicious). The failure model you assume determines how much redundancy and coordination machinery your design actually needs: assuming Byzantine failures when the interview expects fail-stop wastes time building consensus nobody asked for; assuming fail-stop when the requirements imply otherwise misses a real correctness gap.',
  metaphor:    "Four ways a coworker can let a team down. Fail-stop: they call in sick and stay out — the absence is obvious, so you just reassign their work. Crash-recovery: they vanish mid-task with no notice, then reappear later still holding half-finished, possibly stale work that has to be reconciled with whatever happened while they were gone. Omission: they show up and seem fine, but silently drop half their assigned tasks without ever saying anything went wrong. Byzantine: they show up, report every task as done — and some of that work is subtly wrong or actively misleading. That last case is the worst, because you can no longer even trust their own status reports.",
  path:        '/system-design/failure-models-spectrum',
  howItWorks: [
    'Fail-stop: a component crashes and stays down — permanently, or until an operator intervenes. Critically, the failure is cleanly detectable: other nodes can tell it\'s gone (it stops responding to health checks entirely) and route around it with confidence. This is the easiest failure model to design for, because "detect, then failover" is the entire strategy — there\'s no ambiguity about whether the failed node might still be doing something.',
    'Crash-recovery: a component crashes, but may come back later — possibly having lost in-memory state, possibly having missed writes that happened while it was down, possibly rejoining with stale data. This is harder than fail-stop because the system must handle the node\'s *return*, not just its absence: does it need to catch up from a replication log before serving traffic again? Could it have partially applied a write before crashing, leaving inconsistent state on disk? Most real hardware and process crashes are crash-recovery, not fail-stop — a rebooted server rejoins the cluster, it doesn\'t stay gone forever.',
    'Omission failure: a component keeps running and looks healthy, but silently fails to send or receive some messages — a dropped packet, a request that times out with no response, a message queue that loses an item. Unlike fail-stop, there\'s no clean signal that anything is wrong; the system has to infer omission from timeouts and retries, which is why every RPC-based design needs an explicit answer to "what happens if this call times out — was it dropped before or after it took effect?"',
    'Byzantine failure: a component keeps running, responds to requests, and may report success — but its behavior is arbitrary, incorrect, or actively adversarial. It might return wrong answers, disagree with itself to different observers, or actively try to subvert the protocol. This is the hardest model to tolerate: it requires consensus protocols specifically designed to keep functioning even when some fraction of participants lie (PBFT, blockchain consensus) — the standard technique of "just trust replies and take a majority vote" breaks down if a liar can vote too.',
    'Almost all system design interviews assume fail-stop or crash-recovery, not Byzantine — Byzantine fault tolerance is the domain of blockchain, adversarial multi-party systems, and safety-critical aerospace, not "design a URL shortener." Proposing PBFT-style consensus for a typical CRUD service is a red flag, not a strength — it signals a mismatch between the failure model assumed and the one the problem actually implies. The right instinct is: unless the prompt explicitly involves untrusted or adversarial participants, assume crash-recovery and move on.',
    'The assumed failure model directly drives how much redundancy and coordination a design needs — this is where the theory becomes a concrete architectural choice. Fail-stop assumptions justify simple active-passive failover (see `availability-patterns`). Crash-recovery assumptions require replication logs and a recovery/catch-up procedure, not just a health check. Omission assumptions justify retries with idempotency keys. None of this requires Byzantine-tolerant consensus unless a participant might actively lie — naming which model you\'re assuming, out loud, is often the fastest way to justify why your design does or doesn\'t need heavyweight consensus.',
  ],
  keyPoints: [
    'The spectrum, easiest to hardest to tolerate: fail-stop → crash-recovery → omission → Byzantine — each step removes an assumption about how cleanly a failure can be detected',
    'Fail-stop = crashes and stays down, cleanly detectable. Crash-recovery = crashes but may come back holding stale/partial state — this is what most real hardware and process failures actually look like',
    'Omission failures (dropped messages, silent timeouts) are why every RPC-based design needs an explicit idempotency story — "did my write commit before the timeout?" is an omission-failure question',
    'Byzantine failures (arbitrary or malicious behavior) require dedicated consensus protocols (PBFT, blockchain-style) tolerant to lying participants — the standard "take a majority vote" approach assumes voters are honest',
    'Almost every system design interview assumes fail-stop/crash-recovery, not Byzantine — proposing Byzantine-tolerant consensus for an ordinary service is usually a mismatch signal, not a strength, unless the prompt explicitly involves untrusted participants',
    'The assumed failure model is what justifies the redundancy strategy: fail-stop → simple failover (`availability-patterns`); crash-recovery → replication logs + catch-up; omission → retries + idempotency keys',
  ],
  components: [
    {
      id:            'fail-stop',
      title:         'Fail-Stop',
      icon:          '🛑',
      color:         '#10b981',
      animationType: 'failure',
      summary: 'Crashes and stays down — cleanly detectable, easiest to handle',
      detail:  'Other nodes can tell it\'s gone (health checks stop responding entirely) and route around it with confidence. Strategy: detect, then failover. No ambiguity about whether the failed node might still be doing something.',
      stats: [
        { label: 'Detectability', value: 'Clean' },
        { label: 'Recovers?',     value: 'No' },
        { label: 'Handles via',   value: 'Simple failover' },
      ],
    },
    {
      id:            'crash-recovery',
      title:         'Crash-Recovery',
      icon:          '🔁',
      color:         '#3b82f6',
      animationType: 'failure',
      summary: 'Crashes, but may come back holding stale or partial state',
      detail:  'Must handle the node\'s return, not just its absence — catching up from a replication log, reconciling a partially-applied write. Most real hardware/process crashes are this, not fail-stop.',
      stats: [
        { label: 'Detectability', value: 'Clean on crash' },
        { label: 'Recovers?',     value: 'Yes — may be stale' },
        { label: 'Handles via',   value: 'Replication log + catch-up' },
      ],
    },
    {
      id:            'omission',
      title:         'Omission',
      icon:          '📭',
      color:         '#f59e0b',
      animationType: 'failure',
      summary: 'Keeps running, but silently drops some messages',
      detail:  'No clean signal anything is wrong — the system infers omission from timeouts and retries. Every RPC design needs an answer to "was this call applied before or after the timeout?"',
      stats: [
        { label: 'Detectability', value: 'Inferred (timeouts)' },
        { label: 'Looks healthy?', value: 'Yes' },
        { label: 'Handles via',   value: 'Retries + idempotency' },
      ],
    },
    {
      id:            'byzantine',
      title:         'Byzantine',
      icon:          '🎭',
      color:         '#f43f5e',
      animationType: 'failure',
      summary: 'Keeps running and responding — but some responses are wrong or malicious',
      detail:  'The hardest model: requires consensus protocols designed to tolerate lying participants (PBFT, blockchain-style) since a simple majority vote breaks if a liar can vote. Rarely the right assumption outside adversarial/blockchain contexts.',
      stats: [
        { label: 'Detectability', value: 'Hardest' },
        { label: 'Assume by default?', value: 'No' },
        { label: 'Handles via',   value: 'PBFT / blockchain consensus' },
      ],
    },
  ],
}
