export default {
  id:          'dns',
  type:        'concept',
  title:       'DNS Resolution',
  category:    'networking',
  tags:        ['dns', 'networking', 'http', 'internet', 'ip'],
  description: 'How a domain name like google.com resolves to an IP address. DNS is the distributed phonebook of the internet — every HTTP request starts here.',
  metaphor:    'A phonebook lookup chain: your browser asks its local resolver, which fans out to root, TLD, then authoritative servers to find the final IP.',
  path:        '/system-design/dns',
  howItWorks: [
    'The browser checks its own short-lived in-memory cache, then the OS checks /etc/hosts and its resolver cache. Both miss on a first visit, so the query continues out to the network.',
    'The browser sends the query to a recursive resolver — typically assigned by your ISP, or a public one like 8.8.8.8 (Google) or 1.1.1.1 (Cloudflare). The resolver does all the remaining work on the browser\'s behalf.',
    'The resolver asks a root nameserver "who handles .com?" One of 13 anycast root server sets (A–M) answers with a referral to the .com TLD nameservers — root servers know every TLD but no individual domain records.',
    'The resolver asks the .com TLD nameserver, operated by Verisign, which refers it to the domain\'s authoritative nameservers (e.g. ns1.google.com) — the servers the domain owner configured at registration.',
    'The resolver asks the authoritative nameserver directly — the source of truth for that domain — and gets back the A record (e.g. google.com → 142.250.80.46) along with a TTL such as 300 seconds.',
    'The resolver caches the answer for the TTL and returns the IP to the browser. The full uncached lookup takes 20–120 ms; the browser now opens a TCP (then TLS) connection to that IP.',
  ],
  keyPoints: [
    'DNS is hierarchical: root → TLD → authoritative',
    'Recursive resolvers do the heavy lifting on your behalf',
    'TTLs control caching duration at every layer',
    'The full lookup takes 20–120 ms; cached hits are near-instant',
  ],
  components: [
    {
      id:            'resolver',
      title:         'Recursive Resolver',
      icon:          '🔄',
      color:         '#3b82f6',
      animationType: 'router',
      summary: 'Does the recursive legwork on your behalf — walks the whole hierarchy so your browser does not have to',
      detail:  'Your ISP assigns one automatically, or you can point at a public resolver like 8.8.8.8 (Google) or 1.1.1.1 (Cloudflare). It queries root, then TLD, then authoritative nameservers in turn, and caches the final answer for the TTL duration so the next request from any client is instant.',
      stats: [
        { label: 'Examples', value: '8.8.8.8, 1.1.1.1' },
        { label: 'Role',     value: 'Walks the hierarchy' },
        { label: 'Caches',   value: 'For the TTL' },
      ],
    },
    {
      id:            'root',
      title:         'Root Nameserver',
      icon:          '🌳',
      color:         '#f59e0b',
      animationType: 'referral',
      summary: 'The entry point into the hierarchy — knows every TLD, no individual domains',
      detail:  '13 sets of root servers (A–M) are distributed globally via anycast, so a query always lands on a nearby copy. They hold the address of every TLD nameserver (.com, .org, .io...) but nothing about individual domains — their only job is to refer the resolver one level down.',
      stats: [
        { label: 'Server sets',  value: '13 (A–M)' },
        { label: 'Distribution', value: 'Anycast, global' },
        { label: 'Knows',        value: 'TLD servers only' },
      ],
    },
    {
      id:            'tld',
      title:         'TLD Nameserver',
      icon:          '📋',
      color:         '#f43f5e',
      animationType: 'referral',
      summary: 'Manages everything under one suffix — .com, .org, .net — and refers to the registrant\'s authoritative servers',
      detail:  'TLD (Top-Level Domain) nameservers are operated by registries — Verisign runs .com and .net. They know which authoritative nameservers each domain under their TLD has configured, but not the records themselves; they just point the resolver to the next hop.',
      stats: [
        { label: 'Operator (.com)', value: 'Verisign' },
        { label: 'Scope',           value: 'One TLD' },
        { label: 'Returns',         value: 'Authoritative NS' },
      ],
    },
    {
      id:            'authoritative',
      title:         'Authoritative Nameserver',
      icon:          '🏠',
      color:         '#10b981',
      animationType: 'database',
      summary: 'The source of truth — holds the actual DNS records for the domain',
      detail:  'This is the final hop and the only server that actually stores the domain\'s records (A, AAAA, CNAME, MX...). For google.com these are ns1–ns4.google.com, configured by Google itself. Every answer the resolver returns ultimately traces back to a record set here.',
      stats: [
        { label: 'Holds',     value: 'A, AAAA, CNAME, MX' },
        { label: 'Final hop', value: 'Yes' },
        { label: 'Set by',    value: 'Domain owner' },
      ],
    },
    {
      id:            'caching',
      title:         'Caching & TTL',
      icon:          '⏳',
      color:         '#06b6d4',
      animationType: 'ttl',
      summary: 'Every layer caches the answer — browser, OS, resolver — so most lookups never reach the network',
      detail:  'Each DNS record carries a TTL that tells every cache along the way how long it may reuse the answer before re-querying. Browsers cache for roughly 60 seconds, resolvers respect the authoritative TTL (e.g. 300s). A first, fully uncached lookup costs 20–120 ms; every cached hit afterward is near-instant.',
      stats: [
        { label: 'Browser cache',    value: '~60 s TTL' },
        { label: 'Uncached lookup',  value: '20–120 ms' },
        { label: 'Cached lookup',    value: 'Near-instant' },
      ],
    },
  ],
}
