export function buildAcidAndBaseSteps() {
  return [
    {
      type:             'intro',
      activeNodes:      [],
      connections:      {},
      transactionState: null,
      message:          'ACID vs BASE: two models for distributed data consistency',
      detail:           'ACID (Atomicity, Consistency, Isolation, Durability) guarantees strong correctness for every transaction. BASE (Basically Available, Soft state, Eventually consistent) trades strict correctness for higher availability and write throughput. The right model depends entirely on whether partial writes or stale reads cause real harm in your use case.',
    },
    {
      type:             'begin',
      activeNodes:      ['client', 'tx-manager'],
      connections:      { 'client-tx': 'request' },
      transactionState: 'open',
      message:          'BEGIN TRANSACTION: the client opens a transaction unit',
      detail:           'The client sends BEGIN to the Transaction Manager, which opens an isolated execution unit. All subsequent operations are buffered — no other transaction can see their intermediate results. This is the start of ACID\'s Isolation guarantee: concurrent readers see only committed state.',
    },
    {
      type:             'write-1',
      activeNodes:      ['tx-manager', 'database'],
      connections:      { 'client-tx': 'request', 'tx-db': 'request' },
      transactionState: 'writing',
      message:          'Write 1: debit Account A — write buffered, not yet visible',
      detail:           'The Transaction Manager writes the debit to Account A in the database\'s transaction buffer. The new balance is not yet committed — a concurrent reader on Account A still sees the old balance. This is Isolation in action. The write-ahead log (WAL) records the intended change so it can be replayed after a crash.',
    },
    {
      type:             'write-2',
      activeNodes:      ['tx-manager', 'database'],
      connections:      { 'client-tx': 'request', 'tx-db': 'request' },
      transactionState: 'writing',
      message:          'Write 2: credit Account B — both writes buffered atomically',
      detail:           'The credit to Account B is appended to the same transaction. Both writes are held in the buffer together — they will be committed or rolled back as a single atomic unit. Atomicity means money never disappears in transit: debit and credit either both land or both revert.',
    },
    {
      type:             'commit',
      activeNodes:      ['tx-manager', 'database', 'client'],
      connections:      { 'client-tx': 'both', 'tx-db': 'both' },
      transactionState: 'committed',
      message:          'COMMIT: all writes flushed to disk, now visible to all readers',
      detail:           'The Transaction Manager flushes both writes to the WAL on disk, then marks the transaction committed. Only now do both changes become visible to concurrent readers. Durability: even if power fails after COMMIT returns, the WAL ensures both changes survive. This is the moment ACID delivers its full promise.',
    },
    {
      type:             'rollback',
      activeNodes:      ['tx-manager', 'database', 'client'],
      connections:      { 'client-tx': 'response', 'tx-db': 'response' },
      transactionState: 'rolled-back',
      message:          'ROLLBACK: constraint violation detected — all writes reverted',
      detail:           'If a constraint is violated (e.g., Account A balance would go negative, violating a CHECK constraint), the Transaction Manager rolls back all buffered writes. Both the debit and the credit are undone atomically — no intermediate state ever becomes visible. This is the Consistency guarantee: the database always transitions between valid states.',
    },
    {
      type:             'isolation',
      activeNodes:      ['client', 'tx-manager', 'database'],
      connections:      { 'client-tx': 'request', 'tx-db': 'both' },
      transactionState: 'isolating',
      message:          'Isolation levels: Serializable vs Read Committed vs Repeatable Read',
      detail:           'Isolation is a dial. Serializable (full ACID, lowest throughput) ensures no anomalies. Read Committed prevents dirty reads but allows non-repeatable reads. Repeatable Read prevents both but allows phantom rows. Each level trades correctness for concurrency throughput. Most OLTP databases default to Read Committed.',
    },
    {
      type:             'base-intro',
      activeNodes:      ['client', 'database'],
      connections:      { 'client-db': 'request' },
      transactionState: 'base',
      message:          'BASE: write acknowledged immediately, replicas sync asynchronously',
      detail:           'In a BASE system, writes are acknowledged as soon as the primary node receives them — no waiting for replicas to confirm. The primary propagates the change to replicas asynchronously. Readers on different replicas may briefly see different values. This divergence window is typically milliseconds to seconds in practice.',
    },
    {
      type:             'eventual',
      activeNodes:      ['database', 'replica'],
      connections:      { 'db-replica': 'request' },
      transactionState: 'converging',
      message:          'Eventual consistency: replicas converge given no new conflicting writes',
      detail:           '"Eventually consistent" does not mean "might be wrong forever" — it means replicas will converge to the same value given sufficient time and no new conflicting writes. DynamoDB and Cassandra offer tunable consistency: eventual reads are cheap and fast; quorum reads add latency but guarantee the most recent committed value.',
    },
    {
      type:             'trade-offs',
      activeNodes:      ['client', 'tx-manager', 'database', 'replica'],
      connections:      { 'client-tx': 'request', 'tx-db': 'both', 'db-replica': 'request' },
      transactionState: null,
      message:          'When to use ACID vs BASE: match the model to the use case',
      detail:           'Use ACID for financial transfers, inventory counts, booking systems — any domain where partial writes or stale reads cause real harm. Use BASE for social feeds, analytics dashboards, recommendation engines, and user activity logs — domains where a briefly stale read is acceptable and availability trumps strict correctness. Many systems mix both: ACID writes, BASE reads from replicas.',
    },
  ]
}
