export default {
  id:          'networking-basics',
  type:        'concept',
  title:       'Networking Basics',
  category:    'networking',
  tags:        ['networking', 'ip', 'packets', 'routing', 'ttl', 'ports', 'protocols', 'osi', 'bandwidth', 'latency', 'tcp', 'udp', 'bgp'],
  description: 'How computers communicate over a network — IP addresses, packets, routing, and the layered protocol model that governs all internet traffic. Understanding these fundamentals is essential for reasoning about distributed systems: every RPC, database query, and API call is packets traveling through this infrastructure.',
  metaphor:    'The postal system: every envelope has a source address (IP), a destination address, and a return-to-sender limit (TTL). It travels through sorting hubs (routers) that read only the destination and decide the next drop point — never opening the envelope. The mailbox slot number is the port; the mail type (first-class, certified) is the protocol.',
  path:        '/system-design/networking-basics',
  howItWorks: [
    'IP addressing: every device on a network has an IP address — a 32-bit (IPv4) or 128-bit (IPv6) identifier. IPv4 addresses like 192.168.1.1 are divided into a network prefix and a host suffix. CIDR notation (10.0.0.0/24) specifies how many bits are the prefix, giving a subnet of 256 addresses.',
    'Packet structure: data is broken into packets — typically 1,500 bytes on Ethernet (MTU). Each packet has an IP header (src IP, dst IP, TTL, checksum, protocol) and a payload. Larger data is fragmented and reassembled at the destination. The header adds overhead; efficient protocols minimize it.',
    'Hop-by-hop routing: routers forward packets based solely on the destination IP, one hop at a time. Each router consults its routing table — a map of IP prefixes to next-hop addresses — and forwards the packet. No router knows the full path; the path emerges from distributed routing decisions. BGP is the protocol that distributes routing information across autonomous systems.',
    'TTL (Time To Live): a counter in the IP header, decremented by 1 at each router. When TTL reaches 0, the packet is dropped and the router sends an ICMP "Time Exceeded" message back. This prevents routing loops from consuming the network forever. traceroute exploits this: it sends packets with TTL=1, 2, 3... to map each hop along the path.',
    'Ports and sockets: a port is a 16-bit number (0–65535) that identifies a specific service on a host. A socket is the combination of IP + port — the unique endpoint for a connection. Well-known ports: 22 (SSH), 80 (HTTP), 443 (HTTPS), 5432 (PostgreSQL). Ephemeral ports (49152–65535) are auto-assigned by the OS for outgoing connections.',
    'Latency vs bandwidth: latency is the time for one packet to travel from source to destination (measured in milliseconds). Bandwidth is the volume of data that can flow per second (measured in Mbps/Gbps). They are independent — a satellite link can have 100 Mbps bandwidth but 600 ms latency. Latency dominates for small request-response workloads; bandwidth dominates for bulk transfers.',
    'OSI model layers: the 7-layer model separates concerns so that each layer can evolve independently. Layer 3 (Network/IP) handles routing. Layer 4 (Transport/TCP/UDP) handles end-to-end delivery and reliability. Layer 7 (Application/HTTP, DNS, gRPC) defines the protocol your application speaks. Each layer adds its own header. Routers only process up to Layer 3; firewalls and load balancers often inspect up to Layer 4 or 7.',
  ],
  keyPoints: [
    'IP addresses identify hosts; ports identify services. A socket (IP:port pair) uniquely identifies an endpoint — this is why two services cannot bind to the same port on the same IP',
    'Routers make local decisions: each hop consults only its own routing table for the next step. The full path is never known in advance — it emerges hop-by-hop, which is why paths can change mid-flight',
    'TTL prevents routing loops — traceroute exploits TTL to map network hops. A traceroute with 30 hops reveals the full internet path between two points',
    'Latency and bandwidth are orthogonal: optimizing one does not improve the other. CDNs reduce latency by moving data physically closer; fat pipes increase bandwidth but cannot reduce the speed-of-light floor',
    'The MTU (typically 1,500 bytes on Ethernet) determines packet size. Payloads larger than the MTU are fragmented and reassembled — fragmentation is expensive; protocols like QUIC and TCP use path MTU discovery to avoid it',
    'BGP (Border Gateway Protocol) is the routing protocol of the internet — it distributes reachability information between autonomous systems. A BGP misconfiguration can reroute global traffic, making it a frequent source of major outages',
  ],
}
