export function buildNetworkingBasicsSteps() {
  return [
    {
      type:          'intro',
      activeNodes:   [],
      activeEdges:   [],
      edgeDirection: null,
      packet:        null,
      message:       'Networking basics: how data travels from machine to machine',
      detail:        'Every piece of data on the internet travels as a packet — a fixed-size chunk with a header (source IP, destination IP, TTL, checksum) and a payload. Packets hop through routers, each forwarding toward the destination based on a routing table lookup. Nothing travels as a continuous stream — it\'s always broken into discrete packets reassembled at the destination.',
    },
    {
      type:          'create-packet',
      activeNodes:   ['client'],
      activeEdges:   [],
      edgeDirection: null,
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 64, srcPort: 51234, dstPort: 443 },
      message:       'Client creates a packet — src IP, dst IP, TTL, ports',
      detail:        'Your machine builds the packet header: source IP (your local address), destination IP (the server), TTL starting at 64, and ports — 51234 (ephemeral, auto-assigned) for your end, 443 (HTTPS) for the server. The TTL is a loop-prevention counter; each router decrements it by 1 and drops the packet if it reaches 0.',
    },
    {
      type:          'to-router-a',
      activeNodes:   ['client', 'router-a'],
      activeEdges:   [0],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 64, srcPort: 51234, dstPort: 443 },
      message:       'Hop 1: packet sent to your default gateway',
      detail:        'The packet leaves your machine destined for the default gateway — your home router or ISP\'s edge router. Your machine doesn\'t know the full path to the destination; it just hands the packet to its gateway. From here, routing decisions are made hop-by-hop, each router knowing only the next step.',
    },
    {
      type:          'router-a-forward',
      activeNodes:   ['router-a'],
      activeEdges:   [0],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 63, srcPort: 51234, dstPort: 443 },
      message:       'Router A: routing table lookup, TTL 64 → 63',
      detail:        'Router A decrements TTL (64 → 63) and consults its routing table. The table maps destination IP prefixes to next-hop IPs. If TTL hit 0 here instead, Router A would drop the packet and send an ICMP "Time Exceeded" message back — this is exactly how traceroute reconstructs the path.',
    },
    {
      type:          'to-router-b',
      activeNodes:   ['router-a', 'router-b'],
      activeEdges:   [1],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 63, srcPort: 51234, dstPort: 443 },
      message:       'Hop 2: packet enters the internet backbone',
      detail:        'The packet enters backbone infrastructure — high-capacity fiber links run by major ISPs. Backbone routers process billions of packets per second using specialized ASICs. BGP (Border Gateway Protocol) governs how these autonomous systems exchange routing information. The source and destination IPs in the packet header remain unchanged across all hops.',
    },
    {
      type:          'router-b-forward',
      activeNodes:   ['router-b'],
      activeEdges:   [1],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 62, srcPort: 51234, dstPort: 443 },
      message:       'Router B: TTL 63 → 62, routes to destination subnet',
      detail:        'TTL drops to 62. Router B recognizes 142.250.80.0/24 as Google\'s subnet via its BGP-learned routes and forwards directly toward the destination. Routers only inspect the Layer 3 (IP) header — they never touch the payload. This strict separation of layers is what lets TCP, UDP, and other protocols all run over the same IP network.',
    },
    {
      type:          'at-server',
      activeNodes:   ['server'],
      activeEdges:   [2],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 62, srcPort: 51234, dstPort: 443 },
      message:       'Packet arrives at server — delivered to port 443 (HTTPS)',
      detail:        'The packet reaches its destination. The OS inspects the destination port (443) and delivers the payload to the HTTPS process listening on that port. Ports let one IP address run many services simultaneously — 80 for HTTP, 443 for HTTPS, 22 for SSH, 5432 for PostgreSQL. The combination of IP + port uniquely identifies a service endpoint (a socket).',
    },
    {
      type:          'response',
      activeNodes:   ['server', 'router-b', 'router-a', 'client'],
      activeEdges:   [2, 1, 0],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 64, srcPort: 443, dstPort: 51234 },
      message:       'Response: src and dst are swapped — packet travels back',
      detail:        'The response packet reverses source and destination: src=142.250.80.46:443, dst=10.0.0.1:51234. Your client matches it to the original request by the source port (51234). The full round-trip time — from the first byte sent to the first byte received — is latency. Bandwidth is how many bytes per second can flow along this path in parallel. They are independent: a satellite link can have high bandwidth but high latency.',
    },
  ]
}
