export function buildNetworkingBasicsSteps() {
  return [
    {
      type:          'intro',
      activeNodes:   [],
      activeEdges:   [],
      edgeDirection: null,
      packet:        null,
      elapsedMs:     0,
      message:       'Networking basics: how data travels from machine to machine',
      detail:        'Every piece of data on the internet travels as a packet — a fixed-size chunk with a header (source IP, destination IP, TTL, checksum) and a payload. Packets hop through routers, each forwarding toward the destination based on a routing table lookup. Nothing travels as a continuous stream — it\'s always broken into discrete packets reassembled at the destination.',
    },
    {
      type:          'create-packet',
      activeNodes:   ['client'],
      activeEdges:   [],
      edgeDirection: null,
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 64, srcPort: 51234, dstPort: 443 },
      elapsedMs:     0,
      message:       'Client creates a packet — src IP, dst IP, TTL, ports',
      detail:        'Your machine builds the packet header: source IP (your local address), destination IP (the server), TTL starting at 64, and ports — 51234 (ephemeral, auto-assigned) for your end, 443 (HTTPS) for the server. The TTL is a loop-prevention counter; each router decrements it by 1 and drops the packet if it reaches 0.',
    },
    {
      type:          'to-router-a',
      activeNodes:   ['client', 'router-a'],
      activeEdges:   [0],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 64, srcPort: 51234, dstPort: 443 },
      elapsedMs:     4,
      message:       'Hop 1: packet sent to your default gateway',
      detail:        'The packet leaves your machine destined for the default gateway — your home router or ISP\'s edge router. Your machine doesn\'t know the full path to the destination; it just hands the packet to its gateway. From here, routing decisions are made hop-by-hop, each router knowing only the next step.',
    },
    {
      type:          'router-a-forward',
      activeNodes:   ['router-a'],
      activeEdges:   [0],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 63, srcPort: 51234, dstPort: 443 },
      elapsedMs:     4.2,
      message:       'Router A: routing table lookup, TTL 64 → 63',
      detail:        'Router A decrements TTL (64 → 63) and consults its routing table. The table maps destination IP prefixes to next-hop IPs. If TTL hit 0 here instead, Router A would drop the packet and send an ICMP "Time Exceeded" message back — this is exactly how traceroute reconstructs the path.',
    },
    {
      type:          'to-router-b',
      activeNodes:   ['router-a', 'router-b'],
      activeEdges:   [1],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 63, srcPort: 51234, dstPort: 443 },
      elapsedMs:     26,
      message:       'Hop 2: packet enters the internet backbone',
      detail:        'The packet enters backbone infrastructure — high-capacity fiber links run by major ISPs. Backbone routers process billions of packets per second using specialized ASICs. BGP (Border Gateway Protocol) governs how these autonomous systems exchange routing information. The source and destination IPs in the packet header remain unchanged across all hops.',
    },
    {
      type:          'router-b-forward',
      activeNodes:   ['router-b'],
      activeEdges:   [1],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 62, srcPort: 51234, dstPort: 443 },
      elapsedMs:     26.2,
      message:       'Router B: TTL 63 → 62, routes to destination subnet',
      detail:        'TTL drops to 62. Router B recognizes 142.250.80.0/24 as Google\'s subnet via its BGP-learned routes and forwards directly toward the destination. Routers only inspect the Layer 3 (IP) header — they never touch the payload. This strict separation of layers is what lets TCP, UDP, and other protocols all run over the same IP network.',
    },
    {
      type:          'at-server',
      activeNodes:   ['server'],
      activeEdges:   [2],
      edgeDirection: 'forward',
      packet:        { srcIp: '10.0.0.1', dstIp: '142.250.80.46', ttl: 62, srcPort: 51234, dstPort: 443 },
      elapsedMs:     38,
      message:       'Packet arrives at server — delivered to port 443 (HTTPS)',
      detail:        'The packet reaches its destination. The OS inspects the destination port (443) and delivers the payload to the HTTPS process listening on that port. Ports let one IP address run many services simultaneously — 80 for HTTP, 443 for HTTPS, 22 for SSH, 5432 for PostgreSQL. The combination of IP + port uniquely identifies a service endpoint (a socket).',
    },
    {
      type:          'response-create',
      activeNodes:   ['server'],
      activeEdges:   [],
      edgeDirection: null,
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 64, srcPort: 443, dstPort: 51234 },
      elapsedMs:     38,
      message:       'Server builds the response — src and dst are swapped',
      detail:        'The server\'s reply gets its own fresh packet header: src=142.250.80.46:443, dst=10.0.0.1:51234, TTL reset to 64. The response is just as much a routed packet as the request was — it retraces the hop-by-hop journey back, not a special return channel.',
    },
    {
      type:          'to-router-b-back',
      activeNodes:   ['server', 'router-b'],
      activeEdges:   [2],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 64, srcPort: 443, dstPort: 51234 },
      elapsedMs:     50,
      message:       'Return hop 1: response sent toward Router B',
      detail:        'The response leaves the server\'s network the same way any outbound packet does — handed to the nearest router, which forwards it based on the destination IP (now your machine\'s address).',
    },
    {
      type:          'router-b-backward',
      activeNodes:   ['router-b'],
      activeEdges:   [2],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 63, srcPort: 443, dstPort: 51234 },
      elapsedMs:     50.2,
      message:       'Router B: TTL 64 → 63, forwards toward Router A',
      detail:        'Router B decrements TTL again and looks up the next hop toward your ISP — the same routing-table process as the outbound trip, just running in reverse over the backbone.',
    },
    {
      type:          'to-router-a-back',
      activeNodes:   ['router-b', 'router-a'],
      activeEdges:   [1],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 63, srcPort: 443, dstPort: 51234 },
      elapsedMs:     72,
      message:       'Return hop 2: response re-enters the backbone toward Router A',
      detail:        'The backbone link is symmetric in topology but not necessarily in path — return traffic can take a different physical route than outbound traffic took, even between the same two endpoints.',
    },
    {
      type:          'router-a-backward',
      activeNodes:   ['router-a'],
      activeEdges:   [1],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 62, srcPort: 443, dstPort: 51234 },
      elapsedMs:     72.2,
      message:       'Router A: TTL 63 → 62, forwards to your gateway',
      detail:        'Router A — your default gateway — decrements TTL once more and forwards the final hop directly to your machine\'s local network.',
    },
    {
      type:          'to-client-back',
      activeNodes:   ['router-a', 'client'],
      activeEdges:   [0],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 62, srcPort: 443, dstPort: 51234 },
      elapsedMs:     76,
      message:       'Return hop 3: response arrives at your gateway',
      detail:        'The last hop — the packet crosses from your default gateway onto your local machine\'s network interface.',
    },
    {
      type:          'at-client',
      activeNodes:   ['client'],
      activeEdges:   [0],
      edgeDirection: 'backward',
      packet:        { srcIp: '142.250.80.46', dstIp: '10.0.0.1', ttl: 62, srcPort: 443, dstPort: 51234 },
      elapsedMs:     76.2,
      message:       'Response delivered — matched to the request by source port 51234',
      detail:        'Your client matches the response to the original request by the destination port (51234), the ephemeral port it picked at the very start. The full round-trip — from the first byte sent to the first byte received — is latency. Bandwidth is how many bytes per second can flow along this path in parallel; they are independent: a satellite link can have high bandwidth but high latency.',
    },
  ]
}
