export default {
  id:          'tcp-and-udp',
  type:        'concept',
  title:       'TCP and UDP',
  category:    'networking',
  tags:        ['tcp', 'udp', 'transport', 'reliability', 'latency', 'handshake', 'streaming'],
  description: 'The two transport-layer protocols powering almost all internet communication — TCP for reliable ordered delivery, UDP for fast best-effort transmission.',
  metaphor:    'TCP is a phone call — both sides acknowledge, nothing is lost, the conversation is ordered. UDP is a radio broadcast — fast and one-way, some listeners might miss a word but nobody waits to confirm.',
  path:        '/system-design/tcp-and-udp',
  howItWorks: [
    'TCP establishes a connection via the 3-way handshake: SYN (sender), SYN-ACK (receiver), ACK (sender). No application data flows until the handshake completes — this adds 1 RTT of latency before the first byte.',
    'TCP assigns sequence numbers to every byte. The receiver ACKs received bytes and buffers out-of-order segments, delivering them to the application in order. Lost segments are retransmitted on timeout.',
    'Flow control uses the TCP receive window — the receiver advertises its buffer capacity so the sender never overwhelms a slow consumer. Congestion control (slow start, AIMD) prevents overwhelming the network itself.',
    'UDP sends datagrams immediately with an 8-byte header. No connection setup, no ACKs, no ordering, no retransmission. The application receives packets in arrival order — or not at all if dropped.',
    'TCP FIN teardown requires a 4-way exchange (FIN, ACK, FIN, ACK) in each direction. TIME_WAIT state keeps the connection open for 2×MSL to absorb delayed packets — a source of port exhaustion on high-connection-rate servers.',
    'QUIC (HTTP/3) reimplements TCP reliability + TLS encryption in user space over UDP, gaining 0-RTT reconnection, no head-of-line blocking between streams, and faster handshakes than TCP+TLS.',
  ],
  keyPoints: [
    'TCP establishes a connection with a 3-way handshake before sending any data',
    'TCP guarantees ordering, delivery, and error correction — at a latency cost',
    'UDP sends datagrams with no setup, no guarantee, and minimal overhead',
    'Real-time apps (gaming, video calls, DNS lookups) use UDP for speed',
    'File transfers, HTTP, and databases use TCP for reliability',
  ],
  components: [
    {
      id:            'handshake',
      title:         'TCP 3-Way Handshake',
      icon:          '🤝',
      color:         '#3b82f6',
      animationType: 'handshake',
      summary: 'Connection setup before any data can flow — costs exactly one round trip',
      detail:  'The sender sends SYN with a random Initial Sequence Number. The receiver replies SYN-ACK, acknowledging that ISN and sending its own. The sender replies ACK and the connection is established. No application data moves until all three packets complete — on a 100ms RTT link, that is 100ms spent before the first byte.',
      stats: [
        { label: 'Packets', value: 'SYN, SYN-ACK, ACK' },
        { label: 'Cost',    value: '1 RTT' },
        { label: 'ISN',     value: 'Randomized' },
      ],
    },
    {
      id:            'reliable-delivery',
      title:         'Reliable Delivery & Retransmission',
      icon:          '🔢',
      color:         '#8b5cf6',
      animationType: 'packet',
      summary: 'Every byte is numbered, acknowledged, and retransmitted if it goes missing',
      detail:  'TCP assigns a sequence number to every byte sent. The receiver ACKs what it has received and buffers segments that arrive out of order, delivering them to the application strictly in order. If an ACK does not arrive before the retransmission timeout, the sender resends — the application never sees a gap or a duplicate.',
      stats: [
        { label: 'Ordering',  value: 'Sequence numbers' },
        { label: 'Loss',      value: 'Retransmit on timeout' },
        { label: 'Delivers',  value: 'In-order, gap-free' },
      ],
    },
    {
      id:            'flow-congestion',
      title:         'Flow & Congestion Control',
      icon:          '🚦',
      color:         '#06b6d4',
      animationType: 'congestion',
      summary: 'Two independent brakes — one protects the receiver, one protects the network',
      detail:  'Flow control uses the TCP receive window: the receiver advertises how much buffer space it has left, so a fast sender never overwhelms a slow consumer. Congestion control (slow start, then AIMD) is separate — it protects the network itself by probing for available bandwidth and backing off sharply when packets are lost. Together they explain why TCP throughput ramps up rather than starting at full speed.',
      stats: [
        { label: 'Flow control',       value: 'Receive window' },
        { label: 'Congestion control', value: 'Slow start + AIMD' },
        { label: 'Each protects',      value: 'Receiver / network' },
      ],
    },
    {
      id:            'udp',
      title:         'UDP — Connectionless Datagrams',
      icon:          '📡',
      color:         '#10b981',
      animationType: 'cdn',
      summary: 'Fire-and-forget delivery — no handshake, no ordering, minimal overhead',
      detail:  'UDP sends a datagram immediately behind an 8-byte header — no connection setup, no ACKs, no retransmission. The application gets packets in arrival order, or not at all if one is dropped. That trade is exactly right for DNS lookups, video/voice streaming, and online games, where a stale retransmit is worse than a dropped packet.',
      stats: [
        { label: 'Header',  value: '8 bytes' },
        { label: 'Setup',   value: 'None' },
        { label: 'Used by', value: 'DNS, gaming, video' },
      ],
    },
    {
      id:            'quic',
      title:         'QUIC (HTTP/3)',
      icon:          '⚡',
      color:         '#f59e0b',
      animationType: 'quic',
      summary: 'Reliability and encryption reimplemented over UDP, in user space',
      detail:  'QUIC rebuilds TCP-style reliability and TLS encryption on top of UDP, entirely outside the kernel. That unlocks 0-RTT reconnection to a previously-seen server, independent streams with no head-of-line blocking between them, and a faster initial handshake than TCP+TLS. HTTP/3 uses QUIC exclusively — it is the direction web transport is heading.',
      stats: [
        { label: 'Built on',     value: 'UDP' },
        { label: 'Reconnect',   value: '0-RTT' },
        { label: 'HOL blocking', value: 'Per-stream, isolated' },
      ],
    },
  ],
}
