export function buildTcpAndUdpSteps() {
  return [
    {
      type:        'intro',
      activeNodes: [],
      connections: {},
      message:     'TCP and UDP: the two transport-layer protocols powering the internet',
      detail:      'TCP and UDP both run on top of IP at the transport layer. They serve fundamentally different goals: TCP prioritises reliability and order over speed; UDP prioritises speed over reliability. Every networked application chooses one based on its tolerance for packet loss vs latency.',
    },
    {
      type:        'tcp-syn',
      activeNodes: ['sender', 'network'],
      connections: { 'sender-network': 'request' },
      handshakeState: 'syn',
      message:     'TCP Step 1 — SYN: sender initiates the 3-way handshake',
      detail:      'TCP requires a connection before any data flows. The sender sends a SYN (synchronise) packet with its Initial Sequence Number (ISN). This ISN is random — it prevents old packets from a previous connection being mistaken for new ones. Until the handshake completes, no application data is sent.',
    },
    {
      type:        'tcp-synack',
      activeNodes: ['network', 'receiver'],
      connections: { 'network-receiver': 'both' },
      handshakeState: 'syn-ack',
      message:     'TCP Step 2 — SYN-ACK: receiver acknowledges and sends its own SYN',
      detail:      'The receiver responds with SYN-ACK — it acknowledges the sender\'s ISN and sends its own. Both sides now know each other\'s sequence numbers. SYN-ACK is why TCP handshake adds ~1 RTT (round trip time) of latency before any data can flow. On a 100ms RTT link, that\'s 100ms of wasted time before a single byte of payload.',
    },
    {
      type:        'tcp-ack',
      activeNodes: ['sender', 'network', 'receiver'],
      connections: { 'sender-network': 'request', 'network-receiver': 'both' },
      handshakeState: 'established',
      message:     'TCP Step 3 — ACK: connection established, data can now flow',
      detail:      'The sender sends ACK, completing the handshake. The connection is established. TCP tracks every byte sent with sequence numbers and requires acknowledgement. Lost packets are retransmitted. The receiver buffers out-of-order segments and delivers them in order to the application. This is reliable ordered delivery.',
    },
    {
      type:        'tcp-flow',
      activeNodes: ['sender', 'network', 'receiver'],
      connections: { 'sender-network': 'both', 'network-receiver': 'both' },
      handshakeState: 'established',
      message:     'TCP flow control and congestion control',
      detail:      'TCP\'s receive window prevents the sender from overwhelming a slow receiver. Congestion control (slow start, AIMD) prevents overwhelming the network. These mechanisms are why TCP throughput varies — it\'s constantly probing network capacity. HTTP/2 multiplexes streams over one TCP connection to reduce the cost of per-stream head-of-line blocking.',
    },
    {
      type:        'tcp-vs-udp',
      activeNodes: ['sender', 'receiver'],
      connections: { 'sender-network': 'request', 'network-receiver': 'request' },
      handshakeState: null,
      protocolMode: 'udp',
      message:     'UDP — no handshake, fire and forget, minimal overhead',
      detail:      'UDP sends datagrams immediately — 8-byte header vs TCP\'s 20-byte header, no connection state, no retransmission, no ordering. The application receives packets in the order they arrive (or doesn\'t, if they\'re dropped). Total overhead is ~1 RTT less than TCP for the first message. For latency-critical applications, that RTT matters enormously.',
    },
    {
      type:        'udp-use-cases',
      activeNodes: ['sender', 'network', 'receiver'],
      connections: { 'sender-network': 'request', 'network-receiver': 'request' },
      handshakeState: null,
      protocolMode: 'udp',
      message:     'UDP use cases — DNS, video streaming, online gaming',
      detail:      'DNS uses UDP: queries are tiny, one RTT is acceptable, and a lost packet just triggers a retry. Video streaming uses UDP (via RTP/QUIC): a dropped frame is better than pausing to retransmit a frame that\'s already stale. Online games use UDP: a missed position update is replaced by the next one. QUIC (HTTP/3) implements reliability on top of UDP to avoid OS-level TCP limitations.',
    },
    {
      type:        'tcp-teardown',
      activeNodes: ['sender', 'network', 'receiver'],
      connections: { 'sender-network': 'both', 'network-receiver': 'both' },
      handshakeState: 'closing',
      message:     'TCP FIN teardown — graceful 4-way close',
      detail:      'TCP connection closure requires a FIN/ACK exchange in each direction (4 packets total). The sender sends FIN; the receiver ACKs; the receiver sends its own FIN; the sender ACKs. TIME_WAIT state keeps the connection open for 2× MSL (Maximum Segment Lifetime) to absorb delayed packets. This is why high-connection-rate servers hit "too many open files" limits.',
    },
    {
      type:        'quic',
      activeNodes: ['sender', 'network', 'receiver'],
      connections: { 'sender-network': 'both', 'network-receiver': 'both' },
      handshakeState: 'established',
      message:     'QUIC (HTTP/3) — reliability + encryption over UDP, 0-RTT handshake',
      detail:      'QUIC reimplements TCP\'s reliability and TLS\'s encryption in user space on top of UDP. Benefits: 0-RTT reconnection for known servers, no head-of-line blocking (streams are independent), faster connection setup. HTTP/3 uses QUIC exclusively. This is the future of web transport — TCP is a kernel-level legacy that QUIC sidesteps entirely.',
    },
  ]
}
